// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  StyleSheet = 1,
  Declaration = 2,
  PropertyName = 3,
  NumberUnit = 5,
  ColorLiteral = 6,
  StringLiteral = 7,
  Template = 8,
  Interp = 9,
  Member = 10,
  Call = 11,
  Identifier = 12,
  ArgList = 15,
  ArgMember = 16,
  ArgCall = 17,
  ArgIdentifier = 18,
  LineComment = 23
