// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  StyleSheet = 1,
  Declaration = 2,
  PropertyName = 3,
  NumberUnit = 5,
  ColorLiteral = 6,
  StringLiteral = 7,
  Template = 8,
  Call = 9,
  Identifier = 10,
  ArgList = 13,
  ArgCall = 14,
  ArgIdentifier = 15,
  LineComment = 19
