// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  StyleSheet = 1,
  Declaration = 2,
  PropertyName = 3,
  NumberUnit = 5,
  ColorLiteral = 6,
  StringLiteral = 7,
  Template = 8,
  Member = 9,
  Call = 10,
  Identifier = 11,
  ArgList = 14,
  ArgMember = 15,
  ArgCall = 16,
  ArgIdentifier = 17,
  LineComment = 22
