// Auto-derived Window.PathogenLang type declaration.
//
// This file is NOT hand-maintained. The Window.PathogenLang interface is
// derived at type-check time from the built `dist/index.d.ts` surface, which
// is the authoritative type declaration generated by `npm run build` from
// the full src/ tree. When a new language-services function is added to
// src/language-services/index.ts, it appears in the next dist rebuild and
// this file picks it up automatically — no manual sync step.
//
// Why dist/ instead of src/? Importing from src/ would pull the playground
// tsconfig into the main library's source tree and surface pre-existing
// strict-mode issues from parser/evaluator that are unrelated to the
// playground. The dist .d.ts is a clean projection of the public API, and
// `skipLibCheck: true` on the playground tsconfig means any internal noise
// in the generated file is ignored.
//
// See feedback_no_drift_prone_files.md and
// project-docs/developer-experience/playground-language-parity.md.
//
// Runtime note: the browser loads `dist/index.global.js` (IIFE bundle) which
// populates window.PathogenLang with the same surface. These imports are
// `import type` only and are erased by the esbuild micro-transpiler — they
// never reach the browser.

import type * as PathogenLangLib from '../../dist/index';

export {};

declare global {
  interface Window {
    PathogenLang: typeof PathogenLangLib;
  }

  /** Global alias available via ESLint config — same as window.PathogenLang */
  const PathogenLang: Window['PathogenLang'];
}
