// Email transport adapter for OTP delivery.
//
// Primary path: Cloudflare Email Sending (env.EMAIL.send), public beta as of
// April 2026. wrangler.toml block: `[[send_email]] name = "EMAIL"`.
// Pre-req: a verified sending domain configured in the CF Email Service
// dashboard, AUTH_FROM_EMAIL set in wrangler.toml [vars].
//
// Fallback paths:
//   - AUTH_DEV_LOG_OTP=1 — log the code to the worker console instead of (or
//     in addition to) sending. Useful in `wrangler pages dev`.
//   - AUTH_RESEND_API_KEY set — use Resend REST API instead of CF.
//
// Swapping providers should never require touching anything outside this file.

import { EMAIL_WORDMARK_DATA_URL } from './email-wordmark.js';
import type { AuthEnv, EmailAttachment } from './types.js';

// Wordmark is embedded as a CID inline attachment (RFC 2392 + multipart/related).
// This works in all major email clients without depending on an externally
// hosted URL. Gmail strips data: URLs in <img> and image-blocking proxies
// can break externally-hosted images on first send from a new sender. CID
// inline is the universally robust pattern for transactional email.
const WORDMARK_CID = 'wordmark';

// Strip the "data:image/png;base64," prefix to get raw base64 for the
// attachment payload. EMAIL_WORDMARK_DATA_URL is generated by
// scripts/generate-email-wordmark.ts.
const WORDMARK_BASE64 = EMAIL_WORDMARK_DATA_URL.split(',', 2)[1] || '';

const DEFAULT_PRODUCT_NAME = 'Pathogen Studio';

export interface SendOtpResult {
  delivered: boolean;
  via: 'cloudflare' | 'resend' | 'dev-log';
  messageId?: string;
  error?: string;
}

export interface SendOtpContext {
  ip?: string;
  requestedAt?: number; // epoch ms
}

export async function sendOtpEmail(
  env: AuthEnv,
  to: string,
  code: string,
  context: SendOtpContext = {},
): Promise<SendOtpResult> {
  const productName = env.AUTH_PRODUCT_NAME || DEFAULT_PRODUCT_NAME;
  // Code lives in the body, not the subject — subject codes leak via Gmail
  // inbox previews and resemble phishing templates.
  const subject = `Sign in to ${productName}`;
  const text = renderText(productName, code, context);
  const html = renderHtml(productName, code, context);

  if (env.AUTH_DEV_LOG_OTP) {
    // Don't print full code at log level info — keep it visible but obviously dev-only.
    console.log(`[auth] dev OTP for ${to}: ${code}`);
    return { delivered: true, via: 'dev-log' };
  }

  if (env.EMAIL && env.AUTH_FROM_EMAIL) {
    try {
      const attachments: EmailAttachment[] | undefined = WORDMARK_BASE64
        ? [{
            content: WORDMARK_BASE64,
            filename: 'wordmark.png',
            type: 'image/png',
            disposition: 'inline',
            contentId: WORDMARK_CID,
          }]
        : undefined;
      const result = await env.EMAIL.send({
        from: env.AUTH_FROM_EMAIL,
        to,
        subject,
        text,
        html,
        attachments,
      });
      return { delivered: true, via: 'cloudflare', messageId: result.messageId };
    } catch (err) {
      // Fall through to Resend if configured, else surface the error.
      if (!env.AUTH_RESEND_API_KEY) {
        return { delivered: false, via: 'cloudflare', error: (err as Error).message };
      }
      console.warn('[auth] Cloudflare Email Sending failed, falling back to Resend:', err);
    }
  }

  if (env.AUTH_RESEND_API_KEY && env.AUTH_FROM_EMAIL) {
    try {
      const res = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${env.AUTH_RESEND_API_KEY}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          from: env.AUTH_FROM_EMAIL,
          to: [to],
          subject,
          text,
          html,
        }),
      });
      if (!res.ok) {
        const body = await res.text();
        return { delivered: false, via: 'resend', error: `${res.status} ${body}` };
      }
      const json = (await res.json()) as { id?: string };
      return { delivered: true, via: 'resend', messageId: json.id };
    } catch (err) {
      return { delivered: false, via: 'resend', error: (err as Error).message };
    }
  }

  return {
    delivered: false,
    via: 'cloudflare',
    error: 'No email transport configured. Set AUTH_DEV_LOG_OTP=1 in dev, or configure EMAIL binding + AUTH_FROM_EMAIL.',
  };
}

function formatTimestamp(ms: number): string {
  // "May 6, 2026 at 14:30 UTC" — readable + unambiguous, locale-independent.
  const d = new Date(ms);
  const date = d.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    timeZone: 'UTC',
  });
  const time = d.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
    timeZone: 'UTC',
  });
  return `${date} at ${time} UTC`;
}

function buildContextLine(context: SendOtpContext): string {
  const parts: string[] = [];
  if (context.ip && context.ip !== 'unknown') parts.push(`from ${context.ip}`);
  if (context.requestedAt) parts.push(`at ${formatTimestamp(context.requestedAt)}`);
  if (parts.length === 0) return '';
  return `Requested ${parts.join(' ')}.`;
}

function renderText(product: string, code: string, context: SendOtpContext): string {
  const lines: string[] = [
    `Your ${product} 6-digit sign-in code is: ${code}`,
    '',
    `It expires in 10 minutes.`,
  ];
  const ctx = buildContextLine(context);
  if (ctx) {
    lines.push('');
    lines.push(ctx);
  }
  lines.push('');
  lines.push(`If this wasn't you, ignore this email — no action is needed.`);
  lines.push(`Reply to this email to report abuse.`);
  return lines.join('\n');
}

function renderHtml(product: string, code: string, context: SendOtpContext): string {
  const ctxLine = buildContextLine(context);
  const ctxHtml = ctxLine
    ? `<p style="margin:24px 0 4px;color:#475569;font-size:0.875rem;">${escapeHtml(ctxLine)}</p>`
    : '';
  return `<!DOCTYPE html>
<html><body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 24px; background:#f8f9fa; color:#1a1a2e;">
  <div style="max-width:480px;margin:0 auto;background:#ffffff;border-radius:12px;padding:32px;border:1px solid #e2e8f0;">
    <h1 style="margin:0 0 16px;font-size:1.25rem;">Sign in to ${escapeHtml(product)}</h1>
    <p style="margin:0 0 24px;color:#475569;">Use the 6-digit code below to finish signing in. It expires in 10 minutes.</p>
    <div style="font-family: 'Inconsolata', ui-monospace, monospace; font-size:2rem; letter-spacing:0.4em; font-weight:600; text-align:center; padding:16px; border-radius:8px; background:#f1f5f9; user-select:all;">${escapeHtml(code)}</div>
    ${ctxHtml}
    <p style="margin:8px 0 0;color:#64748b;font-size:0.875rem;">If this wasn't you, ignore this email — no action is needed. <a href="mailto:hello@pathogen.studio" style="color:#10b981;text-decoration:none;">Reply</a> to report abuse.</p>
    <hr style="margin:28px 0 16px;border:none;border-top:1px solid #e2e8f0;">
    <div style="text-align:center;">
      <img src="cid:${WORDMARK_CID}" alt="${escapeHtml(product)}" width="140" height="28" style="display:inline-block;height:28px;width:auto;opacity:0.85;">
    </div>
  </div>
</body></html>`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (ch) => {
    switch (ch) {
      case '&': return '&amp;';
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '"': return '&quot;';
      default: return '&#39;';
    }
  });
}
