// AUTO-GENERATED by scripts/generate-completions.ts — DO NOT EDIT
// Source: src/api-surface.ts (enums) + src/pathogen-api.ts (stdlib, types, namespaces)
// Regenerate: npm run generate:completions

import type { CompletionEntry, MemberCompletionSet } from './completion-data-static';

/** Top-level enum name completions (GridPatternType, Easing, etc.) */
export const ENUM_COMPLETIONS: CompletionEntry[] = [
  { label: 'BBoxAnchor', kind: 'variable', detail: 'Bounding box anchor position', boost: 8 },
  { label: 'BlendMode', kind: 'variable', detail: 'CSS blend-mode keyword', boost: 6 },
  { label: 'ConicSpread', kind: 'variable', detail: 'Conic gradient edge behavior', boost: 6 },
  { label: 'Direction', kind: 'variable', detail: 'Rotation direction (CW/CCW)', boost: 8 },
  { label: 'Easing', kind: 'variable', detail: 'Easing function for interpolation', boost: 10 },
  { label: 'GlowMode', kind: 'variable', detail: 'GlowFilter outer/inner mode', boost: 8 },
  { label: 'GradientUnits', kind: 'variable', detail: 'Gradient coordinate system', boost: 6 },
  { label: 'GridPatternType', kind: 'variable', detail: 'Grid cell rendering mode', boost: 10 },
  { label: 'HexagonOrientation', kind: 'variable', detail: 'Hexagon grid orientation', boost: 8 },
  { label: 'InnerFill', kind: 'variable', detail: 'Conic gradient inner fill mode', boost: 6 },
  { label: 'Interpolation', kind: 'variable', detail: 'Color interpolation space', boost: 8 },
  { label: 'MarkerOrient', kind: 'variable', detail: 'Marker orientation mode', boost: 8 },
  { label: 'MarkerPreserveAspectRatio', kind: 'variable', detail: 'Marker viewBox alignment + meet/slice', boost: 4 },
  { label: 'MarkerRefX', kind: 'variable', detail: 'Marker refX keyword position', boost: 6 },
  { label: 'MarkerRefY', kind: 'variable', detail: 'Marker refY keyword position', boost: 6 },
  { label: 'MarkerUnits', kind: 'variable', detail: 'Marker coordinate system', boost: 6 },
  { label: 'NoiseFilterScale', kind: 'variable', detail: 'NoiseFilter scale preset (fine/medium/coarse)', boost: 7 },
  { label: 'NoiseFilterStyle', kind: 'variable', detail: 'NoiseFilter primitive-chain preset', boost: 8 },
  { label: 'SpreadMethod', kind: 'variable', detail: 'Gradient spread method', boost: 8 },
  { label: 'TopoMethod', kind: 'variable', detail: 'Topological gradient method', boost: 6 },
  { label: 'VerticalAnchor', kind: 'variable', detail: 'Text vertical alignment anchor', boost: 8 },
];

/** Enum member completions keyed by enum name */
export const ENUM_MEMBER_MAP: Record<string, CompletionEntry[]> = {
  BBoxAnchor: [
    { label: 'TopLeft', kind: 'constant', detail: 'BBoxAnchor.TopLeft → "top-left"', boost: 8 },
    { label: 'Top', kind: 'constant', detail: 'BBoxAnchor.Top → "top"', boost: 8 },
    { label: 'TopRight', kind: 'constant', detail: 'BBoxAnchor.TopRight → "top-right"', boost: 8 },
    { label: 'Right', kind: 'constant', detail: 'BBoxAnchor.Right → "right"', boost: 8 },
    { label: 'BottomRight', kind: 'constant', detail: 'BBoxAnchor.BottomRight → "bottom-right"', boost: 8 },
    { label: 'Bottom', kind: 'constant', detail: 'BBoxAnchor.Bottom → "bottom"', boost: 8 },
    { label: 'BottomLeft', kind: 'constant', detail: 'BBoxAnchor.BottomLeft → "bottom-left"', boost: 8 },
    { label: 'Left', kind: 'constant', detail: 'BBoxAnchor.Left → "left"', boost: 8 },
    { label: 'Center', kind: 'constant', detail: 'BBoxAnchor.Center → "center"', boost: 8 },
  ],
  BlendMode: [
    { label: 'Normal', kind: 'constant', detail: 'BlendMode.Normal → "normal"', boost: 8 },
    { label: 'Multiply', kind: 'constant', detail: 'BlendMode.Multiply → "multiply"', boost: 8 },
    { label: 'Screen', kind: 'constant', detail: 'BlendMode.Screen → "screen"', boost: 8 },
    { label: 'Overlay', kind: 'constant', detail: 'BlendMode.Overlay → "overlay"', boost: 8 },
    { label: 'ColorBurn', kind: 'constant', detail: 'BlendMode.ColorBurn → "color-burn"', boost: 8 },
    { label: 'ColorDodge', kind: 'constant', detail: 'BlendMode.ColorDodge → "color-dodge"', boost: 8 },
    { label: 'HardLight', kind: 'constant', detail: 'BlendMode.HardLight → "hard-light"', boost: 8 },
    { label: 'SoftLight', kind: 'constant', detail: 'BlendMode.SoftLight → "soft-light"', boost: 8 },
    { label: 'Darken', kind: 'constant', detail: 'BlendMode.Darken → "darken"', boost: 8 },
    { label: 'Lighten', kind: 'constant', detail: 'BlendMode.Lighten → "lighten"', boost: 8 },
    { label: 'Difference', kind: 'constant', detail: 'BlendMode.Difference → "difference"', boost: 8 },
    { label: 'Exclusion', kind: 'constant', detail: 'BlendMode.Exclusion → "exclusion"', boost: 8 },
  ],
  ConicSpread: [
    { label: 'Clamp', kind: 'constant', detail: 'ConicSpread.Clamp → "clamp"', boost: 8 },
    { label: 'Repeat', kind: 'constant', detail: 'ConicSpread.Repeat → "repeat"', boost: 8 },
    { label: 'Transparent', kind: 'constant', detail: 'ConicSpread.Transparent → "transparent"', boost: 8 },
  ],
  Direction: [
    { label: 'CW', kind: 'constant', detail: 'Direction.CW → "cw"', boost: 8 },
    { label: 'CCW', kind: 'constant', detail: 'Direction.CCW → "ccw"', boost: 8 },
  ],
  Easing: [
    { label: 'Linear', kind: 'constant', detail: 'Easing.Linear → "linear"', boost: 8 },
    { label: 'Smoothstep', kind: 'constant', detail: 'Easing.Smoothstep → "smoothstep"', boost: 8 },
    { label: 'EaseIn', kind: 'constant', detail: 'Easing.EaseIn → "ease-in"', boost: 8 },
    { label: 'EaseOut', kind: 'constant', detail: 'Easing.EaseOut → "ease-out"', boost: 8 },
    { label: 'EaseInOut', kind: 'constant', detail: 'Easing.EaseInOut → "ease-in-out"', boost: 8 },
  ],
  GlowMode: [
    { label: 'Outer', kind: 'constant', detail: 'GlowMode.Outer → "outer"', boost: 8 },
    { label: 'Inner', kind: 'constant', detail: 'GlowMode.Inner → "inner"', boost: 8 },
  ],
  GradientUnits: [
    { label: 'ObjectBoundingBox', kind: 'constant', detail: 'GradientUnits.ObjectBoundingBox → "objectBoundingBox"', boost: 8 },
    { label: 'UserSpaceOnUse', kind: 'constant', detail: 'GradientUnits.UserSpaceOnUse → "userSpaceOnUse"', boost: 8 },
  ],
  GridPatternType: [
    { label: 'Shape', kind: 'constant', detail: 'GridPatternType.Shape → "shape"', boost: 8 },
    { label: 'Dot', kind: 'constant', detail: 'GridPatternType.Dot → "dot"', boost: 8 },
    { label: 'Intersection', kind: 'constant', detail: 'GridPatternType.Intersection → "intersection"', boost: 8 },
    { label: 'Partial', kind: 'constant', detail: 'GridPatternType.Partial → "partial"', boost: 8 },
  ],
  HexagonOrientation: [
    { label: 'Edge', kind: 'constant', detail: 'HexagonOrientation.Edge → "edge"', boost: 8 },
    { label: 'Vertex', kind: 'constant', detail: 'HexagonOrientation.Vertex → "vertex"', boost: 8 },
  ],
  InnerFill: [
    { label: 'Transparent', kind: 'constant', detail: 'InnerFill.Transparent → "transparent"', boost: 8 },
    { label: 'TransparentBlend', kind: 'constant', detail: 'InnerFill.TransparentBlend → "transparent-blend"', boost: 8 },
    { label: 'Center', kind: 'constant', detail: 'InnerFill.Center → "center"', boost: 8 },
  ],
  Interpolation: [
    { label: 'SRGB', kind: 'constant', detail: 'Interpolation.SRGB → "srgb"', boost: 8 },
    { label: 'OKLCH', kind: 'constant', detail: 'Interpolation.OKLCH → "oklch"', boost: 8 },
    { label: 'LinearRGB', kind: 'constant', detail: 'Interpolation.LinearRGB → "linearRGB"', boost: 8 },
  ],
  MarkerOrient: [
    { label: 'Auto', kind: 'constant', detail: 'MarkerOrient.Auto → "auto"', boost: 8 },
    { label: 'AutoStartReverse', kind: 'constant', detail: 'MarkerOrient.AutoStartReverse → "auto-start-reverse"', boost: 8 },
  ],
  MarkerPreserveAspectRatio: [
    { label: 'None', kind: 'constant', detail: 'MarkerPreserveAspectRatio.None → "none"', boost: 8 },
    { label: 'XMinYMinMeet', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMinYMinMeet → "xMinYMin meet"', boost: 8 },
    { label: 'XMinYMinSlice', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMinYMinSlice → "xMinYMin slice"', boost: 8 },
    { label: 'XMidYMinMeet', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMidYMinMeet → "xMidYMin meet"', boost: 8 },
    { label: 'XMidYMinSlice', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMidYMinSlice → "xMidYMin slice"', boost: 8 },
    { label: 'XMaxYMinMeet', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMaxYMinMeet → "xMaxYMin meet"', boost: 8 },
    { label: 'XMaxYMinSlice', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMaxYMinSlice → "xMaxYMin slice"', boost: 8 },
    { label: 'XMinYMidMeet', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMinYMidMeet → "xMinYMid meet"', boost: 8 },
    { label: 'XMinYMidSlice', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMinYMidSlice → "xMinYMid slice"', boost: 8 },
    { label: 'XMidYMidMeet', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMidYMidMeet → "xMidYMid meet"', boost: 8 },
    { label: 'XMidYMidSlice', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMidYMidSlice → "xMidYMid slice"', boost: 8 },
    { label: 'XMaxYMidMeet', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMaxYMidMeet → "xMaxYMid meet"', boost: 8 },
    { label: 'XMaxYMidSlice', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMaxYMidSlice → "xMaxYMid slice"', boost: 8 },
    { label: 'XMinYMaxMeet', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMinYMaxMeet → "xMinYMax meet"', boost: 8 },
    { label: 'XMinYMaxSlice', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMinYMaxSlice → "xMinYMax slice"', boost: 8 },
    { label: 'XMidYMaxMeet', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMidYMaxMeet → "xMidYMax meet"', boost: 8 },
    { label: 'XMidYMaxSlice', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMidYMaxSlice → "xMidYMax slice"', boost: 8 },
    { label: 'XMaxYMaxMeet', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMaxYMaxMeet → "xMaxYMax meet"', boost: 8 },
    { label: 'XMaxYMaxSlice', kind: 'constant', detail: 'MarkerPreserveAspectRatio.XMaxYMaxSlice → "xMaxYMax slice"', boost: 8 },
  ],
  MarkerRefX: [
    { label: 'Left', kind: 'constant', detail: 'MarkerRefX.Left → "left"', boost: 8 },
    { label: 'Center', kind: 'constant', detail: 'MarkerRefX.Center → "center"', boost: 8 },
    { label: 'Right', kind: 'constant', detail: 'MarkerRefX.Right → "right"', boost: 8 },
  ],
  MarkerRefY: [
    { label: 'Top', kind: 'constant', detail: 'MarkerRefY.Top → "top"', boost: 8 },
    { label: 'Center', kind: 'constant', detail: 'MarkerRefY.Center → "center"', boost: 8 },
    { label: 'Bottom', kind: 'constant', detail: 'MarkerRefY.Bottom → "bottom"', boost: 8 },
  ],
  MarkerUnits: [
    { label: 'StrokeWidth', kind: 'constant', detail: 'MarkerUnits.StrokeWidth → "strokeWidth"', boost: 8 },
    { label: 'UserSpaceOnUse', kind: 'constant', detail: 'MarkerUnits.UserSpaceOnUse → "userSpaceOnUse"', boost: 8 },
  ],
  NoiseFilterScale: [
    { label: 'Fine', kind: 'constant', detail: 'NoiseFilterScale.Fine → "fine"', boost: 8 },
    { label: 'Medium', kind: 'constant', detail: 'NoiseFilterScale.Medium → "medium"', boost: 8 },
    { label: 'Coarse', kind: 'constant', detail: 'NoiseFilterScale.Coarse → "coarse"', boost: 8 },
  ],
  NoiseFilterStyle: [
    { label: 'Grain', kind: 'constant', detail: 'NoiseFilterStyle.Grain → "grain"', boost: 8 },
    { label: 'Paper', kind: 'constant', detail: 'NoiseFilterStyle.Paper → "paper"', boost: 8 },
    { label: 'Speckle', kind: 'constant', detail: 'NoiseFilterStyle.Speckle → "speckle"', boost: 8 },
    { label: 'Static', kind: 'constant', detail: 'NoiseFilterStyle.Static → "static"', boost: 8 },
    { label: 'Gradient', kind: 'constant', detail: 'NoiseFilterStyle.Gradient → "gradient"', boost: 8 },
  ],
  SpreadMethod: [
    { label: 'Pad', kind: 'constant', detail: 'SpreadMethod.Pad → "pad"', boost: 8 },
    { label: 'Reflect', kind: 'constant', detail: 'SpreadMethod.Reflect → "reflect"', boost: 8 },
    { label: 'Repeat', kind: 'constant', detail: 'SpreadMethod.Repeat → "repeat"', boost: 8 },
  ],
  TopoMethod: [
    { label: 'Distance', kind: 'constant', detail: 'TopoMethod.Distance → "distance"', boost: 8 },
    { label: 'Laplace', kind: 'constant', detail: 'TopoMethod.Laplace → "laplace"', boost: 8 },
  ],
  VerticalAnchor: [
    { label: 'Descender', kind: 'constant', detail: 'VerticalAnchor.Descender → "descender"', boost: 8 },
    { label: 'Baseline', kind: 'constant', detail: 'VerticalAnchor.Baseline → "baseline"', boost: 8 },
    { label: 'Midline', kind: 'constant', detail: 'VerticalAnchor.Midline → "midline"', boost: 8 },
    { label: 'CapHeight', kind: 'constant', detail: 'VerticalAnchor.CapHeight → "cap-height"', boost: 8 },
  ],
};

/** Stdlib function, constructor, namespace, and context-aware completions */
export const STDLIB_COMPLETIONS: CompletionEntry[] = [
  { label: 'Point', kind: 'function', detail: 'Point(x, y) — Create a 2D point', boost: 15 },
  { label: 'PolarVector', kind: 'function', detail: 'PolarVector(angle, distance) — Polar direction/distance', boost: 14 },
  { label: 'Cycler', kind: 'function', detail: 'Cycler(array, shuffle?) — Round-robin iterator', boost: 12 },
  { label: 'CSSVar', kind: 'function', detail: 'CSSVar(\'name\', fallback?) — CSS custom property', boost: 10 },
  { label: 'PathLayer', kind: 'function', detail: 'PathLayer(\'name\') — Path layer constructor', boost: 12 },
  { label: 'TextLayer', kind: 'function', detail: 'TextLayer(\'name\') — Text layer constructor', boost: 12 },
  { label: 'GroupLayer', kind: 'function', detail: 'GroupLayer(\'name\') — Group layer constructor', boost: 12 },
  { label: 'NoiseFilter', kind: 'function', detail: 'NoiseFilter() — Grain/paper/speckle/static/grainy-gradient noise filter', boost: 11 },
  { label: 'GlowFilter', kind: 'function', detail: 'GlowFilter() — Outer or inner soft glow', boost: 11 },
  { label: 'EmbossFilter', kind: 'function', detail: 'EmbossFilter() — Light-source-based embossed surface', boost: 11 },
  { label: 'ElevationShadowFilter', kind: 'function', detail: 'ElevationShadowFilter() — Material-style layered depth shadow', boost: 11 },
  { label: 'InnerShadowFilter', kind: 'function', detail: 'InnerShadowFilter() — Inset shadow (capability CSS drop-shadow() lacks)', boost: 11 },
  { label: 'PixelateFilter', kind: 'function', detail: 'PixelateFilter(width?, height?, radius?) — Mosaic / pixelation filter', boost: 11 },
  { label: 'polarPoint', kind: 'function', detail: 'polarPoint(angle, distance) — Point at polar offset', boost: 14 },
  { label: 'polarOffset', kind: 'function', detail: 'polarOffset(angle, distance) — Relative polar offset', boost: 14 },
  { label: 'polarMove', kind: 'function', detail: 'polarMove(angle, distance) — Move in polar direction', boost: 14 },
  { label: 'polarLine', kind: 'function', detail: 'polarLine(angle, distance) — Line in polar direction', boost: 14 },
  { label: 'arcFromCenter', kind: 'function', detail: 'arcFromCenter(dcx, dcy, r, start, end, cw) — Arc from center', boost: 12 },
  { label: 'arcFromPolarOffset', kind: 'function', detail: 'arcFromPolarOffset(angle, radius, sweepAngle) — Arc from polar center', boost: 12 },
  { label: 'tangentLine', kind: 'function', detail: 'tangentLine(length) — Line following tangent', boost: 12 },
  { label: 'tangentArc', kind: 'function', detail: 'tangentArc(radius, sweepAngle) — Arc from tangent', boost: 12 },
  { label: 'heading', kind: 'function', detail: 'heading(angle) — Set heading direction', boost: 10 },
  { label: 'turn', kind: 'function', detail: 'turn(delta) — Turn heading by delta', boost: 10 },
  { label: 'circle', kind: 'function', detail: 'circle(cx, cy, r) — Draw circle', boost: 15 },
  { label: 'rect', kind: 'function', detail: 'rect(x, y, w, h) — Draw rectangle', boost: 15 },
  { label: 'roundRect', kind: 'function', detail: 'roundRect(x, y, w, h, r) — Rounded rectangle', boost: 13 },
  { label: 'polygon', kind: 'function', detail: 'polygon(cx, cy, r, sides) — Regular polygon', boost: 13 },
  { label: 'star', kind: 'function', detail: 'star(cx, cy, outer, inner, points) — Star shape', boost: 13 },
  { label: 'quadratic', kind: 'function', detail: 'quadratic(x1, y1, cx, cy, x2, y2) — Quadratic bezier', boost: 10 },
  { label: 'cubic', kind: 'function', detail: 'cubic(x1, y1, c1x, c1y, c2x, c2y, x2, y2) — Cubic bezier', boost: 10 },
  { label: 'arc', kind: 'function', detail: 'arc(rx, ry, rot, large, sweep, x, y) — Arc command', boost: 10 },
  { label: 'line', kind: 'function', detail: 'line(x1, y1, x2, y2) — Line segment', boost: 10 },
  { label: 'moveTo', kind: 'function', detail: 'moveTo(x, y) — Move command', boost: 8 },
  { label: 'lineTo', kind: 'function', detail: 'lineTo(x, y) — Line command', boost: 8 },
  { label: 'closePath', kind: 'function', detail: 'closePath() — Close path (Z)', boost: 8 },
  { label: 'cubicSpline', kind: 'function', detail: 'cubicSpline(points) — Smooth cubic spline', boost: 8 },
  { label: 'quadSpline', kind: 'function', detail: 'quadSpline(start, points, end) — Smooth quad spline', boost: 8 },
  { label: 'clippedQuadSpline', kind: 'function', detail: 'clippedQuadSpline(start, points, end) — Clipped quad spline', boost: 8 },
  { label: 'polarCubicBezier', kind: 'function', detail: 'polarCubicBezier(start, pv1, pv2, end) — Polar cubic bezier', boost: 8 },
  { label: 'radialWedge', kind: 'function', detail: 'radialWedge(innerR, outerR, fromAngle, toAngle, cornerR) — Annular sector', boost: 8 },
  { label: 'squareGrid', kind: 'function', detail: 'squareGrid(type, x, y, w, h, cellSize) — Square grid', boost: 8 },
  { label: 'triangleGrid', kind: 'function', detail: 'triangleGrid(type, x, y, w, h, cellSize) — Triangle grid', boost: 8 },
  { label: 'hexagonGrid', kind: 'function', detail: 'hexagonGrid(type, x, y, w, h, cellSize, orient?) — Hex grid', boost: 8 },
  { label: 'sin', kind: 'function', detail: 'sin(x) — Sine', boost: 12 },
  { label: 'cos', kind: 'function', detail: 'cos(x) — Cosine', boost: 12 },
  { label: 'tan', kind: 'function', detail: 'tan(x) — Tangent', boost: 8 },
  { label: 'asin', kind: 'function', detail: 'asin(x) — Arc sine', boost: 6 },
  { label: 'acos', kind: 'function', detail: 'acos(x) — Arc cosine', boost: 6 },
  { label: 'atan', kind: 'function', detail: 'atan(x) — Arc tangent', boost: 6 },
  { label: 'atan2', kind: 'function', detail: 'atan2(y, x) — Two-argument arc tangent', boost: 8 },
  { label: 'sinh', kind: 'function', detail: 'sinh(x) — Hyperbolic sine', boost: 6 },
  { label: 'cosh', kind: 'function', detail: 'cosh(x) — Hyperbolic cosine', boost: 6 },
  { label: 'tanh', kind: 'function', detail: 'tanh(x) — Hyperbolic tangent', boost: 6 },
  { label: 'PI', kind: 'function', detail: 'PI() — Returns pi', boost: 12 },
  { label: 'TAU', kind: 'function', detail: 'TAU() — Returns 2*pi', boost: 12 },
  { label: 'E', kind: 'function', detail: 'E() — Returns e', boost: 8 },
  { label: 'mpi', kind: 'function', detail: 'mpi(x) — Multiply by pi', boost: 6 },
  { label: 'deg', kind: 'function', detail: 'deg(radians) — Convert radians to degrees', boost: 10 },
  { label: 'rad', kind: 'function', detail: 'rad(degrees) — Convert degrees to radians', boost: 10 },
  { label: 'normalizeAngle', kind: 'function', detail: 'normalizeAngle(angle) — Normalize to [0, 2pi)', boost: 6 },
  { label: 'lerp', kind: 'function', detail: 'lerp(a, b, t) — Linear interpolation', boost: 14 },
  { label: 'clamp', kind: 'function', detail: 'clamp(value, min, max) — Constrain to range', boost: 14 },
  { label: 'map', kind: 'function', detail: 'map(val, inMin, inMax, outMin, outMax) — Map between ranges', boost: 12 },
  { label: 'floor', kind: 'function', detail: 'floor(x) — Round down', boost: 8 },
  { label: 'ceil', kind: 'function', detail: 'ceil(x) — Round up', boost: 8 },
  { label: 'round', kind: 'function', detail: 'round(x) — Round to nearest', boost: 8 },
  { label: 'trunc', kind: 'function', detail: 'trunc(x) — Truncate decimal', boost: 6 },
  { label: 'abs', kind: 'function', detail: 'abs(x) — Absolute value', boost: 10 },
  { label: 'sign', kind: 'function', detail: 'sign(x) — Sign (-1, 0, or 1)', boost: 6 },
  { label: 'min', kind: 'function', detail: 'min(a, b, ...) — Minimum', boost: 10 },
  { label: 'max', kind: 'function', detail: 'max(a, b, ...) — Maximum', boost: 10 },
  { label: 'polarX', kind: 'function', detail: 'polarX(cx, angle, radius) — X component of polar coordinate', boost: 8 },
  { label: 'polarY', kind: 'function', detail: 'polarY(cy, angle, radius) — Y component of polar coordinate', boost: 8 },
  { label: 'random', kind: 'function', detail: 'random() — Random 0-1', boost: 8 },
  { label: 'randomRange', kind: 'function', detail: 'randomRange(min, max) — Random in range', boost: 8 },
  { label: 'exp', kind: 'function', detail: 'exp(x) — e^x', boost: 6 },
  { label: 'log', kind: 'function', detail: 'log(...) — Natural log or debug log', boost: 8 },
  { label: 'log10', kind: 'function', detail: 'log10(x) — Base-10 log', boost: 6 },
  { label: 'log2', kind: 'function', detail: 'log2(x) — Base-2 log', boost: 6 },
  { label: 'pow', kind: 'function', detail: 'pow(x, y) — x^y', boost: 8 },
  { label: 'sqrt', kind: 'function', detail: 'sqrt(x) — Square root', boost: 10 },
  { label: 'cbrt', kind: 'function', detail: 'cbrt(x) — Cube root', boost: 6 },
  { label: 'ctx', kind: 'variable', detail: 'ctx — Path context (position, start, heading)', boost: 16 },
  { label: 'Object', kind: 'variable', detail: 'Object — Static methods (keys, values, entries)', boost: 6 },
  { label: 'Color', kind: 'variable', detail: 'Color — Color creation and manipulation', boost: 8 },
];

/** Type member completion sets keyed by Pathogen type name */
export const TYPE_MEMBERS: Record<string, MemberCompletionSet> = {
  'ColorInstance': {
    properties: [
      { label: 'css', kind: 'property', detail: 'CSS color string', boost: 8 },
      { label: 'hex', kind: 'property', detail: 'Hex color value', boost: 8 },
      { label: 'oklch', kind: 'property', detail: 'OKLCH representation', boost: 8 },
      { label: 'hsl', kind: 'property', detail: 'HSL representation', boost: 8 },
      { label: 'rgb', kind: 'property', detail: 'RGB representation', boost: 8 },
      { label: 'lightness', kind: 'property', detail: 'OKLCH lightness (0-1)', boost: 8 },
      { label: 'chroma', kind: 'property', detail: 'OKLCH chroma', boost: 8 },
      { label: 'hue', kind: 'property', detail: 'OKLCH hue (degrees)', boost: 8 },
      { label: 'a', kind: 'property', detail: 'Alpha channel (0-1)', boost: 8 },
    ],
    methods: [
      { label: 'lighten', kind: 'function', detail: 'lighten(amount) — Lighten color', boost: 8 },
      { label: 'darken', kind: 'function', detail: 'darken(amount) — Darken color', boost: 8 },
      { label: 'saturate', kind: 'function', detail: 'saturate(factor) — Increase saturation', boost: 8 },
      { label: 'desaturate', kind: 'function', detail: 'desaturate(factor) — Decrease saturation', boost: 8 },
      { label: 'alpha', kind: 'function', detail: 'alpha(value) — Set alpha channel', boost: 8 },
      { label: 'hueShift', kind: 'function', detail: 'hueShift(degrees) — Rotate hue', boost: 8 },
      { label: 'complement', kind: 'function', detail: 'complement() — Complementary color', boost: 8 },
      { label: 'mix', kind: 'function', detail: 'mix(other, t) — Mix with another color', boost: 8 },
      { label: 'analogous', kind: 'function', detail: 'analogous(angle?) — Analogous color harmony (3 colors)', boost: 8 },
      { label: 'triadic', kind: 'function', detail: 'triadic() — Triadic color harmony (3 colors)', boost: 8 },
      { label: 'tetradic', kind: 'function', detail: 'tetradic() — Tetradic color harmony (4 colors)', boost: 8 },
      { label: 'splitComplementary', kind: 'function', detail: 'splitComplementary(angle?) — Split complementary harmony (3 colors)', boost: 8 },
    ],
  },
  'BoundingBox': {
    properties: [
      { label: 'x', kind: 'property', detail: 'X position', boost: 8 },
      { label: 'y', kind: 'property', detail: 'Y position', boost: 8 },
      { label: 'width', kind: 'property', detail: 'Width', boost: 8 },
      { label: 'height', kind: 'property', detail: 'Height', boost: 8 },
    ],
    methods: [

    ],
  },
  'Point': {
    properties: [
      { label: 'x', kind: 'property', detail: 'X coordinate', boost: 8 },
      { label: 'y', kind: 'property', detail: 'Y coordinate', boost: 8 },
    ],
    methods: [
      { label: 'translate', kind: 'function', detail: 'translate(dx, dy) — Offset point', boost: 8 },
      { label: 'rotate', kind: 'function', detail: 'rotate(angle, origin?) — Rotate around point', boost: 8 },
      { label: 'distanceTo', kind: 'function', detail: 'distanceTo(other) — Euclidean distance', boost: 8 },
      { label: 'angleTo', kind: 'function', detail: 'angleTo(other) — Angle to other point', boost: 8 },
      { label: 'lerp', kind: 'function', detail: 'lerp(other, t) — Interpolate toward point', boost: 8 },
      { label: 'midpoint', kind: 'function', detail: 'midpoint(other) — Midpoint between two points', boost: 8 },
      { label: 'polarTranslate', kind: 'function', detail: 'polarTranslate(angle, distance) — Polar offset', boost: 8 },
      { label: 'offset', kind: 'function', detail: 'offset(other) — Get {dx, dy} delta', boost: 8 },
    ],
  },
  'array': {
    properties: [
      { label: 'length', kind: 'property', detail: 'Number of elements', boost: 8 },
    ],
    methods: [
      { label: 'push', kind: 'function', detail: 'push(item) — Add to end', boost: 8 },
      { label: 'pop', kind: 'function', detail: 'pop() — Remove and return last element', boost: 8 },
      { label: 'shift', kind: 'function', detail: 'shift() — Remove and return first element', boost: 8 },
      { label: 'unshift', kind: 'function', detail: 'unshift(item) — Add to beginning', boost: 8 },
      { label: 'empty', kind: 'function', detail: 'empty() — Check if array is empty', boost: 8 },
      { label: 'map', kind: 'function', detail: 'map {|item| ...} — Transform elements', boost: 8 },
      { label: 'reduce', kind: 'function', detail: 'reduce(init) {|acc, item| ...} — Reduce', boost: 8 },
      { label: 'mapSlice', kind: 'function', detail: 'mapSlice(length) — Sliding window slices', boost: 8 },
      { label: 'slice', kind: 'function', detail: 'slice(start, end?) — Get sub-array', boost: 8 },
    ],
  },
  'string': {
    properties: [
      { label: 'length', kind: 'property', detail: 'String length', boost: 8 },
    ],
    methods: [
      { label: 'split', kind: 'function', detail: 'split() — Split into character array', boost: 8 },
      { label: 'append', kind: 'function', detail: 'append(str) — Concatenate', boost: 8 },
      { label: 'prepend', kind: 'function', detail: 'prepend(str) — Prepend string', boost: 8 },
      { label: 'includes', kind: 'function', detail: 'includes(str) — Check if contains', boost: 8 },
      { label: 'slice', kind: 'function', detail: 'slice(start, end?) — Get substring', boost: 8 },
      { label: 'empty', kind: 'function', detail: 'empty() — Check if empty', boost: 8 },
    ],
  },
  'PathBlock': {
    properties: [
      { label: 'length', kind: 'property', detail: 'Path length', boost: 8 },
      { label: 'vertices', kind: 'property', detail: 'Vertex points', boost: 8 },
      { label: 'subPathCount', kind: 'property', detail: 'Number of subpaths', boost: 8 },
      { label: 'subPathCommands', kind: 'property', detail: 'Array of command objects', boost: 8 },
      { label: 'startPoint', kind: 'property', detail: 'First point', boost: 8 },
      { label: 'endPoint', kind: 'property', detail: 'Last point', boost: 8 },
      { label: 'advanceWidth', kind: 'property', detail: 'Glyph advance width', boost: 8 },
      { label: 'contours', kind: 'property', detail: 'Per-contour PathBlocks', boost: 8 },
    ],
    methods: [
      { label: 'draw', kind: 'function', detail: 'draw() — Emit path data', boost: 8 },
      { label: 'drawTo', kind: 'function', detail: 'drawTo(layerName) — Emit to layer', boost: 8 },
      { label: 'get', kind: 'function', detail: 'get(t) — Sample point at t', boost: 8 },
      { label: 'tangent', kind: 'function', detail: 'tangent(t) — Tangent angle at t', boost: 8 },
      { label: 'normal', kind: 'function', detail: 'normal(t) — Normal angle at t', boost: 8 },
      { label: 'partition', kind: 'function', detail: 'partition(n) — Split into segments', boost: 8 },
      { label: 'reverse', kind: 'function', detail: 'reverse() — Reverse direction', boost: 8 },
      { label: 'boundingBox', kind: 'function', detail: 'boundingBox() — Get bounding box', boost: 8 },
      { label: 'offset', kind: 'function', detail: 'offset(distance) — Offset path', boost: 8 },
      { label: 'mirror', kind: 'function', detail: 'mirror(angle) — Mirror path', boost: 8 },
      { label: 'scale', kind: 'function', detail: 'scale(sx, sy) — Scale path', boost: 8 },
      { label: 'rotateAtVertexIndex', kind: 'function', detail: 'rotateAtVertexIndex(index, angle) — Rotate at vertex', boost: 8 },
      { label: 'subPath', kind: 'function', detail: 'subPath(startT, endT) — Extract sub-path', boost: 8 },
      { label: 'project', kind: 'function', detail: 'project(x, y) — Project to position', boost: 8 },
      { label: 'chamfer', kind: 'function', detail: 'chamfer(distance) — Chamfer all corners', boost: 8 },
      { label: 'chamferAtVertex', kind: 'function', detail: 'chamferAtVertex(index, distance) — Chamfer at vertex', boost: 8 },
      { label: 'fillet', kind: 'function', detail: 'fillet(radius) — Round all corners', boost: 8 },
      { label: 'filletAtVertex', kind: 'function', detail: 'filletAtVertex(index, radius) — Round at vertex', boost: 8 },
      { label: 'ellipticalFillet', kind: 'function', detail: 'ellipticalFillet(rx, ry) — Elliptical fillet', boost: 8 },
      { label: 'ellipticalFilletAtVertex', kind: 'function', detail: 'ellipticalFilletAtVertex(index, rx, ry) — Elliptical fillet at vertex', boost: 8 },
      { label: 'union', kind: 'function', detail: 'union(other) — Boolean union', boost: 8 },
      { label: 'difference', kind: 'function', detail: 'difference(other) — Boolean difference', boost: 8 },
      { label: 'intersection', kind: 'function', detail: 'intersection(other) — Boolean intersection', boost: 8 },
      { label: 'xor', kind: 'function', detail: 'xor(other) — Boolean XOR', boost: 8 },
      { label: 'intersects', kind: 'function', detail: 'intersects(other) — Check for intersections', boost: 8 },
      { label: 'intersectionPoints', kind: 'function', detail: 'intersectionPoints(other) — Get intersection points', boost: 8 },
    ],
  },
  'PolarVector': {
    properties: [
      { label: 'angle', kind: 'property', detail: 'Angle in radians', boost: 8 },
      { label: 'distance', kind: 'property', detail: 'Distance magnitude', boost: 8 },
    ],
    methods: [
      { label: 'turn', kind: 'function', detail: 'turn(delta) — Turn by angle delta', boost: 8 },
      { label: 'scale', kind: 'function', detail: 'scale(factor) — Scale distance', boost: 8 },
      { label: 'mirror', kind: 'function', detail: 'mirror() — Flip direction', boost: 8 },
    ],
  },
  'Cycler': {
    properties: [
      { label: 'length', kind: 'property', detail: 'Number of elements', boost: 8 },
    ],
    methods: [
      { label: 'pick', kind: 'function', detail: 'pick() — Get next element', boost: 8 },
    ],
  },
  'SVGFragment': {
    properties: [

    ],
    methods: [
      { label: 'insert', kind: 'function', detail: 'insert() — Insert fragment into layer', boost: 8 },
    ],
  },
  'TextLayer': {
    properties: [
      { label: 'name', kind: 'property', detail: 'Layer name', boost: 8 },
      { label: 'styles', kind: 'property', detail: 'Style block', boost: 8 },
    ],
    methods: [
      { label: 'apply', kind: 'function', detail: 'apply { } — Send text commands to this layer', boost: 8 },
    ],
  },
  'PathLayer': {
    properties: [
      { label: 'name', kind: 'property', detail: 'Layer name', boost: 8 },
      { label: 'styles', kind: 'property', detail: 'Style block', boost: 8 },
      { label: 'ctx', kind: 'property', detail: 'Path context (position, heading, transform)', boost: 8 },
    ],
    methods: [
      { label: 'apply', kind: 'function', detail: 'apply { } — Send path commands to this layer', boost: 8 },
    ],
  },
  'GroupLayer': {
    properties: [
      { label: 'name', kind: 'property', detail: 'Layer name', boost: 8 },
      { label: 'styles', kind: 'property', detail: 'Style block', boost: 8 },
      { label: 'ctx', kind: 'property', detail: 'Path context (position, heading, transform)', boost: 8 },
    ],
    methods: [
      { label: 'apply', kind: 'function', detail: 'apply { } — Send commands to this layer', boost: 8 },
      { label: 'append', kind: 'function', detail: 'append(layer) — Add child layer', boost: 8 },
    ],
  },
  'PathContext': {
    properties: [
      { label: 'position', kind: 'property', detail: 'Current pen position {x, y}', boost: 8 },
      { label: 'start', kind: 'property', detail: 'Subpath start position {x, y}', boost: 8 },
      { label: 'heading', kind: 'property', detail: 'Current heading angle', boost: 10 },
      { label: 'tangentAngle', kind: 'property', detail: 'Tangent angle at current position', boost: 8 },
      { label: 'transform', kind: 'property', detail: 'Layer transform state', boost: 8 },
      { label: 'commands', kind: 'property', detail: 'Array of executed commands', boost: 8 },
    ],
    methods: [

    ],
  },
  'ObjectValue': {
    properties: [
      { label: 'length', kind: 'property', detail: 'Number of properties', boost: 8 },
    ],
    methods: [
      { label: 'has', kind: 'function', detail: 'has(key) — Check if key exists', boost: 8 },
    ],
  },
  'ProjectedText': {
    properties: [
      { label: 'elementCount', kind: 'property', detail: 'Number of text elements', boost: 8 },
      { label: 'styles', kind: 'property', detail: 'Style block', boost: 8 },
      { label: 'origin', kind: 'property', detail: 'Origin point', boost: 8 },
    ],
    methods: [
      { label: 'translate', kind: 'function', detail: 'translate(dx, dy) — Offset projected text', boost: 8 },
    ],
  },
  'CSSVar': {
    properties: [

    ],
    methods: [

    ],
  },
  'NoiseFilter': {
    properties: [
      { label: 'id', kind: 'property', detail: 'Filter id (auto-generated as pathogen-noise-N)', boost: 8 },
      { label: 'style', kind: 'property', detail: 'Preset chain + parameter baseline', boost: 8 },
      { label: 'scale', kind: 'property', detail: 'baseFrequency — \'fine\' | \'medium\' | \'coarse\' | number', boost: 8 },
      { label: 'octaves', kind: 'property', detail: 'numOctaves — 1..10', boost: 8 },
      { label: 'amount', kind: 'property', detail: 'Visible intensity 0..1', boost: 8 },
      { label: 'monochrome', kind: 'property', detail: 'Strip color variance via luminanceToAlpha', boost: 8 },
      { label: 'seed', kind: 'property', detail: 'feTurbulence seed (auto-derived from id by default)', boost: 8 },
      { label: 'blend', kind: 'property', detail: 'Final blend mode against SourceGraphic', boost: 8 },
      { label: 'contrast', kind: 'property', detail: 'Post-noise contrast pump (1 = no pump)', boost: 8 },
      { label: 'stitch', kind: 'property', detail: 'stitchTiles toggle', boost: 8 },
    ],
    methods: [

    ],
  },
  'GlowFilter': {
    properties: [
      { label: 'id', kind: 'property', detail: 'Filter id (auto-generated as pathogen-glow-N)', boost: 8 },
      { label: 'mode', kind: 'property', detail: 'Outer halo or inner edge light', boost: 8 },
      { label: 'color', kind: 'property', detail: 'Glow color', boost: 8 },
      { label: 'radius', kind: 'property', detail: 'Blur stdDeviation', boost: 8 },
      { label: 'spread', kind: 'property', detail: 'Pre-blur morphology radius (0 = no morphology)', boost: 8 },
      { label: 'opacity', kind: 'property', detail: 'Glow strength 0..1', boost: 8 },
    ],
    methods: [

    ],
  },
  'EmbossFilter': {
    properties: [
      { label: 'id', kind: 'property', detail: 'Filter id (auto-generated as pathogen-emboss-N)', boost: 8 },
      { label: 'angle', kind: 'property', detail: 'Light azimuth', boost: 8 },
      { label: 'elevation', kind: 'property', detail: 'Light elevation', boost: 10 },
      { label: 'depth', kind: 'property', detail: 'surfaceScale — visual depth of the bevel', boost: 8 },
      { label: 'strength', kind: 'property', detail: 'specularConstant — highlight brightness', boost: 8 },
      { label: 'shininess', kind: 'property', detail: 'specularExponent — highlight sharpness (>= 1)', boost: 8 },
      { label: 'lightColor', kind: 'property', detail: 'Simulated light color', boost: 8 },
      { label: 'smooth', kind: 'property', detail: 'Pre-blur stdDeviation for softer bevel edges', boost: 8 },
    ],
    methods: [

    ],
  },
  'ElevationShadowFilter': {
    properties: [
      { label: 'id', kind: 'property', detail: 'Filter id (auto-generated as pathogen-elevation-shadow-N)', boost: 8 },
      { label: 'elevation', kind: 'property', detail: 'Depth from the surface, 0..24', boost: 8 },
      { label: 'color', kind: 'property', detail: 'Shadow color', boost: 8 },
      { label: 'direction', kind: 'property', detail: 'Shadow direction (default 90deg = down)', boost: 8 },
      { label: 'tightness', kind: 'property', detail: 'Scales the per-layer distance/blur ratios (1.0 = Material defaults)', boost: 8 },
    ],
    methods: [

    ],
  },
  'InnerShadowFilter': {
    properties: [
      { label: 'id', kind: 'property', detail: 'Filter id (auto-generated as pathogen-inner-shadow-N)', boost: 8 },
      { label: 'offsetX', kind: 'property', detail: 'Horizontal offset', boost: 8 },
      { label: 'offsetY', kind: 'property', detail: 'Vertical offset', boost: 8 },
      { label: 'blur', kind: 'property', detail: 'Blur stdDeviation', boost: 8 },
      { label: 'color', kind: 'property', detail: 'Shadow color', boost: 8 },
      { label: 'opacity', kind: 'property', detail: 'Shadow strength 0..1', boost: 8 },
    ],
    methods: [

    ],
  },
  'PixelateFilter': {
    properties: [
      { label: 'id', kind: 'property', detail: 'Filter id (auto-generated as pathogen-pixelate-N)', boost: 8 },
      { label: 'width', kind: 'property', detail: 'Horizontal stride between samples', boost: 8 },
      { label: 'height', kind: 'property', detail: 'Vertical stride between samples', boost: 8 },
      { label: 'radius', kind: 'property', detail: 'Dilation radius', boost: 8 },
    ],
    methods: [

    ],
  },
};

/** Namespace member completion sets keyed by namespace name */
export const NAMESPACE_MEMBERS: Record<string, MemberCompletionSet> = {
  'Object': {
    properties: [

    ],
    methods: [
      { label: 'keys', kind: 'function', detail: 'Object.keys(obj) — Get keys', boost: 8 },
      { label: 'values', kind: 'function', detail: 'Object.values(obj) — Get values', boost: 8 },
      { label: 'entries', kind: 'function', detail: 'Object.entries(obj) — Key-value pairs', boost: 8 },
      { label: 'delete', kind: 'function', detail: 'Object.delete(obj, key) — Remove key', boost: 8 },
      { label: 'has', kind: 'function', detail: 'Object.has(obj, key) — Check if key exists', boost: 8 },
    ],
  },
  'Color': {
    properties: [

    ],
    methods: [
      { label: 'mix', kind: 'function', detail: 'Color.mix(c1, c2, t) — Interpolate colors', boost: 8 },
      { label: 'palette', kind: 'function', detail: 'Color.palette(color, n) — Generate palette', boost: 8 },
      { label: 'lightDark', kind: 'function', detail: 'Color.lightDark(light, dark) — Theme-aware color', boost: 8 },
    ],
  },
};

/** Signature data for signature help, keyed by function name */
export const SIGNATURE_DATA: Record<string, { label: string; params: string[]; doc: string }> = {
  'Point': { label: 'Point(x, y)', params: ['x', 'y'], doc: 'Point(x, y) — Create a 2D point' },
  'PolarVector': { label: 'PolarVector(angle, distance)', params: ['angle', 'distance'], doc: 'PolarVector(angle, distance) — Polar direction/distance' },
  'Cycler': { label: 'Cycler(array, shuffle)', params: ['array', 'shuffle'], doc: 'Cycler(array, shuffle?) — Round-robin iterator' },
  'CSSVar': { label: 'CSSVar(name, fallback)', params: ['name', 'fallback'], doc: 'CSSVar(\'name\', fallback?) — CSS custom property' },
  'PathLayer': { label: 'PathLayer(name)', params: ['name'], doc: 'PathLayer(\'name\') — Path layer constructor' },
  'TextLayer': { label: 'TextLayer(name)', params: ['name'], doc: 'TextLayer(\'name\') — Text layer constructor' },
  'GroupLayer': { label: 'GroupLayer(name)', params: ['name'], doc: 'GroupLayer(\'name\') — Group layer constructor' },
  'NoiseFilter': { label: 'NoiseFilter()', params: [], doc: 'NoiseFilter() — Grain/paper/speckle/static/grainy-gradient noise filter' },
  'GlowFilter': { label: 'GlowFilter()', params: [], doc: 'GlowFilter() — Outer or inner soft glow' },
  'EmbossFilter': { label: 'EmbossFilter()', params: [], doc: 'EmbossFilter() — Light-source-based embossed surface' },
  'ElevationShadowFilter': { label: 'ElevationShadowFilter()', params: [], doc: 'ElevationShadowFilter() — Material-style layered depth shadow' },
  'InnerShadowFilter': { label: 'InnerShadowFilter()', params: [], doc: 'InnerShadowFilter() — Inset shadow (capability CSS drop-shadow() lacks)' },
  'PixelateFilter': { label: 'PixelateFilter(width, height, radius)', params: ['width', 'height', 'radius'], doc: 'PixelateFilter(width?, height?, radius?) — Mosaic / pixelation filter' },
  'polarPoint': { label: 'polarPoint(angle, distance)', params: ['angle', 'distance'], doc: 'polarPoint(angle, distance) — Point at polar offset' },
  'polarOffset': { label: 'polarOffset(angle, distance)', params: ['angle', 'distance'], doc: 'polarOffset(angle, distance) — Relative polar offset' },
  'polarMove': { label: 'polarMove(angle, distance)', params: ['angle', 'distance'], doc: 'polarMove(angle, distance) — Move in polar direction' },
  'polarLine': { label: 'polarLine(angle, distance)', params: ['angle', 'distance'], doc: 'polarLine(angle, distance) — Line in polar direction' },
  'arcFromCenter': { label: 'arcFromCenter(dcx, dcy, r, start, end, cw)', params: ['dcx', 'dcy', 'r', 'start', 'end', 'cw'], doc: 'arcFromCenter(dcx, dcy, r, start, end, cw) — Arc from center' },
  'arcFromPolarOffset': { label: 'arcFromPolarOffset(angle, radius, sweepAngle)', params: ['angle', 'radius', 'sweepAngle'], doc: 'arcFromPolarOffset(angle, radius, sweepAngle) — Arc from polar center' },
  'tangentLine': { label: 'tangentLine(length)', params: ['length'], doc: 'tangentLine(length) — Line following tangent' },
  'tangentArc': { label: 'tangentArc(radius, sweepAngle)', params: ['radius', 'sweepAngle'], doc: 'tangentArc(radius, sweepAngle) — Arc from tangent' },
  'heading': { label: 'heading(angle)', params: ['angle'], doc: 'heading(angle) — Set heading direction' },
  'turn': { label: 'turn(delta)', params: ['delta'], doc: 'turn(delta) — Turn heading by delta' },
  'circle': { label: 'circle(cx, cy, r)', params: ['cx', 'cy', 'r'], doc: 'circle(cx, cy, r) — Draw circle' },
  'rect': { label: 'rect(x, y, w, h)', params: ['x', 'y', 'w', 'h'], doc: 'rect(x, y, w, h) — Draw rectangle' },
  'roundRect': { label: 'roundRect(x, y, w, h, r)', params: ['x', 'y', 'w', 'h', 'r'], doc: 'roundRect(x, y, w, h, r) — Rounded rectangle' },
  'polygon': { label: 'polygon(cx, cy, r, sides)', params: ['cx', 'cy', 'r', 'sides'], doc: 'polygon(cx, cy, r, sides) — Regular polygon' },
  'star': { label: 'star(cx, cy, outer, inner, points)', params: ['cx', 'cy', 'outer', 'inner', 'points'], doc: 'star(cx, cy, outer, inner, points) — Star shape' },
  'quadratic': { label: 'quadratic(x1, y1, cx, cy, x2, y2)', params: ['x1', 'y1', 'cx', 'cy', 'x2', 'y2'], doc: 'quadratic(x1, y1, cx, cy, x2, y2) — Quadratic bezier' },
  'cubic': { label: 'cubic(x1, y1, c1x, c1y, c2x, c2y, x2, y2)', params: ['x1', 'y1', 'c1x', 'c1y', 'c2x', 'c2y', 'x2', 'y2'], doc: 'cubic(x1, y1, c1x, c1y, c2x, c2y, x2, y2) — Cubic bezier' },
  'arc': { label: 'arc(rx, ry, rot, large, sweep, x, y)', params: ['rx', 'ry', 'rot', 'large', 'sweep', 'x', 'y'], doc: 'arc(rx, ry, rot, large, sweep, x, y) — Arc command' },
  'line': { label: 'line(x1, y1, x2, y2)', params: ['x1', 'y1', 'x2', 'y2'], doc: 'line(x1, y1, x2, y2) — Line segment' },
  'moveTo': { label: 'moveTo(x, y)', params: ['x', 'y'], doc: 'moveTo(x, y) — Move command' },
  'lineTo': { label: 'lineTo(x, y)', params: ['x', 'y'], doc: 'lineTo(x, y) — Line command' },
  'closePath': { label: 'closePath()', params: [], doc: 'closePath() — Close path (Z)' },
  'cubicSpline': { label: 'cubicSpline(points)', params: ['points'], doc: 'cubicSpline(points) — Smooth cubic spline' },
  'quadSpline': { label: 'quadSpline(start, points, end)', params: ['start', 'points', 'end'], doc: 'quadSpline(start, points, end) — Smooth quad spline' },
  'clippedQuadSpline': { label: 'clippedQuadSpline(start, points, end)', params: ['start', 'points', 'end'], doc: 'clippedQuadSpline(start, points, end) — Clipped quad spline' },
  'polarCubicBezier': { label: 'polarCubicBezier(start, pv1, pv2, end)', params: ['start', 'pv1', 'pv2', 'end'], doc: 'polarCubicBezier(start, pv1, pv2, end) — Polar cubic bezier' },
  'radialWedge': { label: 'radialWedge(innerR, outerR, fromAngle, toAngle, cornerR)', params: ['innerR', 'outerR', 'fromAngle', 'toAngle', 'cornerR'], doc: 'radialWedge(innerR, outerR, fromAngle, toAngle, cornerR) — Annular sector' },
  'squareGrid': { label: 'squareGrid(type, x, y, w, h, cellSize)', params: ['type', 'x', 'y', 'w', 'h', 'cellSize'], doc: 'squareGrid(type, x, y, w, h, cellSize) — Square grid' },
  'triangleGrid': { label: 'triangleGrid(type, x, y, w, h, cellSize)', params: ['type', 'x', 'y', 'w', 'h', 'cellSize'], doc: 'triangleGrid(type, x, y, w, h, cellSize) — Triangle grid' },
  'hexagonGrid': { label: 'hexagonGrid(type, x, y, w, h, cellSize, orient)', params: ['type', 'x', 'y', 'w', 'h', 'cellSize', 'orient'], doc: 'hexagonGrid(type, x, y, w, h, cellSize, orient?) — Hex grid' },
  'sin': { label: 'sin(x)', params: ['x'], doc: 'sin(x) — Sine' },
  'cos': { label: 'cos(x)', params: ['x'], doc: 'cos(x) — Cosine' },
  'tan': { label: 'tan(x)', params: ['x'], doc: 'tan(x) — Tangent' },
  'asin': { label: 'asin(x)', params: ['x'], doc: 'asin(x) — Arc sine' },
  'acos': { label: 'acos(x)', params: ['x'], doc: 'acos(x) — Arc cosine' },
  'atan': { label: 'atan(x)', params: ['x'], doc: 'atan(x) — Arc tangent' },
  'atan2': { label: 'atan2(y, x)', params: ['y', 'x'], doc: 'atan2(y, x) — Two-argument arc tangent' },
  'sinh': { label: 'sinh(x)', params: ['x'], doc: 'sinh(x) — Hyperbolic sine' },
  'cosh': { label: 'cosh(x)', params: ['x'], doc: 'cosh(x) — Hyperbolic cosine' },
  'tanh': { label: 'tanh(x)', params: ['x'], doc: 'tanh(x) — Hyperbolic tangent' },
  'PI': { label: 'PI()', params: [], doc: 'PI() — Returns pi' },
  'TAU': { label: 'TAU()', params: [], doc: 'TAU() — Returns 2*pi' },
  'E': { label: 'E()', params: [], doc: 'E() — Returns e' },
  'mpi': { label: 'mpi(x)', params: ['x'], doc: 'mpi(x) — Multiply by pi' },
  'deg': { label: 'deg(radians)', params: ['radians'], doc: 'deg(radians) — Convert radians to degrees' },
  'rad': { label: 'rad(degrees)', params: ['degrees'], doc: 'rad(degrees) — Convert degrees to radians' },
  'normalizeAngle': { label: 'normalizeAngle(angle)', params: ['angle'], doc: 'normalizeAngle(angle) — Normalize to [0, 2pi)' },
  'lerp': { label: 'lerp(a, b, t)', params: ['a', 'b', 't'], doc: 'lerp(a, b, t) — Linear interpolation' },
  'clamp': { label: 'clamp(value, min, max)', params: ['value', 'min', 'max'], doc: 'clamp(value, min, max) — Constrain to range' },
  'map': { label: 'map(val, inMin, inMax, outMin, outMax)', params: ['val', 'inMin', 'inMax', 'outMin', 'outMax'], doc: 'map(val, inMin, inMax, outMin, outMax) — Map between ranges' },
  'floor': { label: 'floor(x)', params: ['x'], doc: 'floor(x) — Round down' },
  'ceil': { label: 'ceil(x)', params: ['x'], doc: 'ceil(x) — Round up' },
  'round': { label: 'round(x)', params: ['x'], doc: 'round(x) — Round to nearest' },
  'trunc': { label: 'trunc(x)', params: ['x'], doc: 'trunc(x) — Truncate decimal' },
  'abs': { label: 'abs(x)', params: ['x'], doc: 'abs(x) — Absolute value' },
  'sign': { label: 'sign(x)', params: ['x'], doc: 'sign(x) — Sign (-1, 0, or 1)' },
  'min': { label: 'min(values)', params: ['values'], doc: 'min(a, b, ...) — Minimum' },
  'max': { label: 'max(values)', params: ['values'], doc: 'max(a, b, ...) — Maximum' },
  'polarX': { label: 'polarX(cx, angle, radius)', params: ['cx', 'angle', 'radius'], doc: 'polarX(cx, angle, radius) — X component of polar coordinate' },
  'polarY': { label: 'polarY(cy, angle, radius)', params: ['cy', 'angle', 'radius'], doc: 'polarY(cy, angle, radius) — Y component of polar coordinate' },
  'random': { label: 'random()', params: [], doc: 'random() — Random 0-1' },
  'randomRange': { label: 'randomRange(min, max)', params: ['min', 'max'], doc: 'randomRange(min, max) — Random in range' },
  'exp': { label: 'exp(x)', params: ['x'], doc: 'exp(x) — e^x' },
  'log': { label: 'log(x)', params: ['x'], doc: 'log(...) — Natural log or debug log' },
  'log10': { label: 'log10(x)', params: ['x'], doc: 'log10(x) — Base-10 log' },
  'log2': { label: 'log2(x)', params: ['x'], doc: 'log2(x) — Base-2 log' },
  'pow': { label: 'pow(x, y)', params: ['x', 'y'], doc: 'pow(x, y) — x^y' },
  'sqrt': { label: 'sqrt(x)', params: ['x'], doc: 'sqrt(x) — Square root' },
  'cbrt': { label: 'cbrt(x)', params: ['x'], doc: 'cbrt(x) — Cube root' },
};
