// AUTO-GENERATED by scripts/generate-completions.ts — DO NOT EDIT
// Source: src/api-surface.ts (enums) + src/pathogen-api.ts (stdlib, types, namespaces)
// Regenerate: npm run generate:completions

import type { CompletionEntry, MemberCompletionSet } from './completion-data';

/** Top-level enum name completions (GridPatternType, Easing, etc.) */
export const ENUM_COMPLETIONS: CompletionEntry[] = [
  { label: 'BBoxAnchor', kind: 'variable', detail: 'Bounding box anchor position', boost: 8 },
  { label: 'ConicSpread', kind: 'variable', detail: 'Conic gradient edge behavior', boost: 6 },
  { label: 'Direction', kind: 'variable', detail: 'Rotation direction (CW/CCW)', boost: 8 },
  { label: 'Easing', kind: 'variable', detail: 'Easing function for interpolation', boost: 10 },
  { label: 'GradientUnits', kind: 'variable', detail: 'Gradient coordinate system', boost: 6 },
  { label: 'GridPatternType', kind: 'variable', detail: 'Grid cell rendering mode', boost: 10 },
  { label: 'HexagonOrientation', kind: 'variable', detail: 'Hexagon grid orientation', boost: 8 },
  { label: 'InnerFill', kind: 'variable', detail: 'Conic gradient inner fill mode', boost: 6 },
  { label: 'Interpolation', kind: 'variable', detail: 'Color interpolation space', boost: 8 },
  { label: 'SpreadMethod', kind: 'variable', detail: 'Gradient spread method', boost: 8 },
  { label: 'TopoMethod', kind: 'variable', detail: 'Topological gradient method', boost: 6 },
  { label: 'VerticalAnchor', kind: 'variable', detail: 'Text vertical alignment anchor', boost: 8 },
];

/** Enum member completions keyed by enum name */
export const ENUM_MEMBER_MAP: Record<string, CompletionEntry[]> = {
  BBoxAnchor: [
    { label: 'TopLeft', kind: 'constant', detail: 'BBoxAnchor.TopLeft → "top-left"', boost: 8 },
    { label: 'Top', kind: 'constant', detail: 'BBoxAnchor.Top → "top"', boost: 8 },
    { label: 'TopRight', kind: 'constant', detail: 'BBoxAnchor.TopRight → "top-right"', boost: 8 },
    { label: 'Right', kind: 'constant', detail: 'BBoxAnchor.Right → "right"', boost: 8 },
    { label: 'BottomRight', kind: 'constant', detail: 'BBoxAnchor.BottomRight → "bottom-right"', boost: 8 },
    { label: 'Bottom', kind: 'constant', detail: 'BBoxAnchor.Bottom → "bottom"', boost: 8 },
    { label: 'BottomLeft', kind: 'constant', detail: 'BBoxAnchor.BottomLeft → "bottom-left"', boost: 8 },
    { label: 'Left', kind: 'constant', detail: 'BBoxAnchor.Left → "left"', boost: 8 },
    { label: 'Center', kind: 'constant', detail: 'BBoxAnchor.Center → "center"', boost: 8 },
  ],
  ConicSpread: [
    { label: 'Clamp', kind: 'constant', detail: 'ConicSpread.Clamp → "clamp"', boost: 8 },
    { label: 'Repeat', kind: 'constant', detail: 'ConicSpread.Repeat → "repeat"', boost: 8 },
    { label: 'Transparent', kind: 'constant', detail: 'ConicSpread.Transparent → "transparent"', boost: 8 },
  ],
  Direction: [
    { label: 'CW', kind: 'constant', detail: 'Direction.CW → "cw"', boost: 8 },
    { label: 'CCW', kind: 'constant', detail: 'Direction.CCW → "ccw"', boost: 8 },
  ],
  Easing: [
    { label: 'Linear', kind: 'constant', detail: 'Easing.Linear → "linear"', boost: 8 },
    { label: 'Smoothstep', kind: 'constant', detail: 'Easing.Smoothstep → "smoothstep"', boost: 8 },
    { label: 'EaseIn', kind: 'constant', detail: 'Easing.EaseIn → "ease-in"', boost: 8 },
    { label: 'EaseOut', kind: 'constant', detail: 'Easing.EaseOut → "ease-out"', boost: 8 },
    { label: 'EaseInOut', kind: 'constant', detail: 'Easing.EaseInOut → "ease-in-out"', boost: 8 },
  ],
  GradientUnits: [
    { label: 'ObjectBoundingBox', kind: 'constant', detail: 'GradientUnits.ObjectBoundingBox → "objectBoundingBox"', boost: 8 },
    { label: 'UserSpaceOnUse', kind: 'constant', detail: 'GradientUnits.UserSpaceOnUse → "userSpaceOnUse"', boost: 8 },
  ],
  GridPatternType: [
    { label: 'Shape', kind: 'constant', detail: 'GridPatternType.Shape → "shape"', boost: 8 },
    { label: 'Dot', kind: 'constant', detail: 'GridPatternType.Dot → "dot"', boost: 8 },
    { label: 'Intersection', kind: 'constant', detail: 'GridPatternType.Intersection → "intersection"', boost: 8 },
    { label: 'Partial', kind: 'constant', detail: 'GridPatternType.Partial → "partial"', boost: 8 },
  ],
  HexagonOrientation: [
    { label: 'Edge', kind: 'constant', detail: 'HexagonOrientation.Edge → "edge"', boost: 8 },
    { label: 'Vertex', kind: 'constant', detail: 'HexagonOrientation.Vertex → "vertex"', boost: 8 },
  ],
  InnerFill: [
    { label: 'Transparent', kind: 'constant', detail: 'InnerFill.Transparent → "transparent"', boost: 8 },
    { label: 'TransparentBlend', kind: 'constant', detail: 'InnerFill.TransparentBlend → "transparent-blend"', boost: 8 },
    { label: 'Center', kind: 'constant', detail: 'InnerFill.Center → "center"', boost: 8 },
  ],
  Interpolation: [
    { label: 'SRGB', kind: 'constant', detail: 'Interpolation.SRGB → "srgb"', boost: 8 },
    { label: 'OKLCH', kind: 'constant', detail: 'Interpolation.OKLCH → "oklch"', boost: 8 },
    { label: 'LinearRGB', kind: 'constant', detail: 'Interpolation.LinearRGB → "linearRGB"', boost: 8 },
  ],
  SpreadMethod: [
    { label: 'Pad', kind: 'constant', detail: 'SpreadMethod.Pad → "pad"', boost: 8 },
    { label: 'Reflect', kind: 'constant', detail: 'SpreadMethod.Reflect → "reflect"', boost: 8 },
    { label: 'Repeat', kind: 'constant', detail: 'SpreadMethod.Repeat → "repeat"', boost: 8 },
  ],
  TopoMethod: [
    { label: 'Distance', kind: 'constant', detail: 'TopoMethod.Distance → "distance"', boost: 8 },
    { label: 'Laplace', kind: 'constant', detail: 'TopoMethod.Laplace → "laplace"', boost: 8 },
  ],
  VerticalAnchor: [
    { label: 'Descender', kind: 'constant', detail: 'VerticalAnchor.Descender → "descender"', boost: 8 },
    { label: 'Baseline', kind: 'constant', detail: 'VerticalAnchor.Baseline → "baseline"', boost: 8 },
    { label: 'Midline', kind: 'constant', detail: 'VerticalAnchor.Midline → "midline"', boost: 8 },
    { label: 'CapHeight', kind: 'constant', detail: 'VerticalAnchor.CapHeight → "cap-height"', boost: 8 },
  ],
};

/** Stdlib function, constructor, namespace, and context-aware completions */
export const STDLIB_COMPLETIONS: CompletionEntry[] = [
  { label: 'Point', kind: 'function', detail: 'Point(x, y) — Create a 2D point', boost: 15 },
  { label: 'PolarVector', kind: 'function', detail: 'PolarVector(angle, distance) — Polar direction/distance', boost: 14 },
  { label: 'Cycler', kind: 'function', detail: 'Cycler(array, shuffle?) — Round-robin iterator', boost: 12 },
  { label: 'CSSVar', kind: 'function', detail: 'CSSVar(\'name\', fallback?) — CSS custom property', boost: 10 },
  { label: 'PathLayer', kind: 'function', detail: 'PathLayer(\'name\') — Path layer constructor', boost: 12 },
  { label: 'TextLayer', kind: 'function', detail: 'TextLayer(\'name\') — Text layer constructor', boost: 12 },
  { label: 'GroupLayer', kind: 'function', detail: 'GroupLayer(\'name\') — Group layer constructor', boost: 12 },
  { label: 'polarPoint', kind: 'function', detail: 'polarPoint(angle, distance) — Point at polar offset', boost: 14 },
  { label: 'polarOffset', kind: 'function', detail: 'polarOffset(angle, distance) — Relative polar offset', boost: 14 },
  { label: 'polarMove', kind: 'function', detail: 'polarMove(angle, distance) — Move in polar direction', boost: 14 },
  { label: 'polarLine', kind: 'function', detail: 'polarLine(angle, distance) — Line in polar direction', boost: 14 },
  { label: 'arcFromCenter', kind: 'function', detail: 'arcFromCenter(dcx, dcy, r, start, end, cw) — Arc from center', boost: 12 },
  { label: 'arcFromPolarOffset', kind: 'function', detail: 'arcFromPolarOffset(angle, radius, sweepAngle) — Arc from polar center', boost: 12 },
  { label: 'tangentLine', kind: 'function', detail: 'tangentLine(length) — Line following tangent', boost: 12 },
  { label: 'tangentArc', kind: 'function', detail: 'tangentArc(radius, sweepAngle) — Arc from tangent', boost: 12 },
  { label: 'heading', kind: 'function', detail: 'heading(angle) — Set heading direction', boost: 10 },
  { label: 'turn', kind: 'function', detail: 'turn(delta) — Turn heading by delta', boost: 10 },
  { label: 'circle', kind: 'function', detail: 'circle(cx, cy, r) — Draw circle', boost: 15 },
  { label: 'rect', kind: 'function', detail: 'rect(x, y, w, h) — Draw rectangle', boost: 15 },
  { label: 'roundRect', kind: 'function', detail: 'roundRect(x, y, w, h, r) — Rounded rectangle', boost: 13 },
  { label: 'polygon', kind: 'function', detail: 'polygon(cx, cy, r, sides) — Regular polygon', boost: 13 },
  { label: 'star', kind: 'function', detail: 'star(cx, cy, outer, inner, points) — Star shape', boost: 13 },
  { label: 'quadratic', kind: 'function', detail: 'quadratic(x1, y1, cx, cy, x2, y2) — Quadratic bezier', boost: 10 },
  { label: 'cubic', kind: 'function', detail: 'cubic(x1, y1, c1x, c1y, c2x, c2y, x2, y2) — Cubic bezier', boost: 10 },
  { label: 'arc', kind: 'function', detail: 'arc(rx, ry, rot, large, sweep, x, y) — Arc command', boost: 10 },
  { label: 'line', kind: 'function', detail: 'line(x1, y1, x2, y2) — Line segment', boost: 10 },
  { label: 'moveTo', kind: 'function', detail: 'moveTo(x, y) — Move command', boost: 8 },
  { label: 'lineTo', kind: 'function', detail: 'lineTo(x, y) — Line command', boost: 8 },
  { label: 'closePath', kind: 'function', detail: 'closePath() — Close path (Z)', boost: 8 },
  { label: 'cubicSpline', kind: 'function', detail: 'cubicSpline(points) — Smooth cubic spline', boost: 8 },
  { label: 'quadSpline', kind: 'function', detail: 'quadSpline(start, points, end) — Smooth quad spline', boost: 8 },
  { label: 'clippedQuadSpline', kind: 'function', detail: 'clippedQuadSpline(start, points, end) — Clipped quad spline', boost: 8 },
  { label: 'polarCubicBezier', kind: 'function', detail: 'polarCubicBezier(start, pv1, pv2, end) — Polar cubic bezier', boost: 8 },
  { label: 'radialWedge', kind: 'function', detail: 'radialWedge(innerR, outerR, fromAngle, toAngle, cornerR) — Annular sector', boost: 8 },
  { label: 'squareGrid', kind: 'function', detail: 'squareGrid(type, x, y, w, h, cellSize) — Square grid', boost: 8 },
  { label: 'triangleGrid', kind: 'function', detail: 'triangleGrid(type, x, y, w, h, cellSize) — Triangle grid', boost: 8 },
  { label: 'hexagonGrid', kind: 'function', detail: 'hexagonGrid(type, x, y, w, h, cellSize, orient?) — Hex grid', boost: 8 },
  { label: 'sin', kind: 'function', detail: 'sin(x) — Sine', boost: 12 },
  { label: 'cos', kind: 'function', detail: 'cos(x) — Cosine', boost: 12 },
  { label: 'tan', kind: 'function', detail: 'tan(x) — Tangent', boost: 8 },
  { label: 'asin', kind: 'function', detail: 'asin(x) — Arc sine', boost: 6 },
  { label: 'acos', kind: 'function', detail: 'acos(x) — Arc cosine', boost: 6 },
  { label: 'atan', kind: 'function', detail: 'atan(x) — Arc tangent', boost: 6 },
  { label: 'atan2', kind: 'function', detail: 'atan2(y, x) — Two-argument arc tangent', boost: 8 },
  { label: 'sinh', kind: 'function', detail: 'sinh(x) — Hyperbolic sine', boost: 6 },
  { label: 'cosh', kind: 'function', detail: 'cosh(x) — Hyperbolic cosine', boost: 6 },
  { label: 'tanh', kind: 'function', detail: 'tanh(x) — Hyperbolic tangent', boost: 6 },
  { label: 'PI', kind: 'function', detail: 'PI() — Returns pi', boost: 12 },
  { label: 'TAU', kind: 'function', detail: 'TAU() — Returns 2*pi', boost: 12 },
  { label: 'E', kind: 'function', detail: 'E() — Returns e', boost: 8 },
  { label: 'mpi', kind: 'function', detail: 'mpi(x) — Multiply by pi', boost: 6 },
  { label: 'deg', kind: 'function', detail: 'deg(radians) — Convert radians to degrees', boost: 10 },
  { label: 'rad', kind: 'function', detail: 'rad(degrees) — Convert degrees to radians', boost: 10 },
  { label: 'normalizeAngle', kind: 'function', detail: 'normalizeAngle(angle) — Normalize to [0, 2pi)', boost: 6 },
  { label: 'lerp', kind: 'function', detail: 'lerp(a, b, t) — Linear interpolation', boost: 14 },
  { label: 'clamp', kind: 'function', detail: 'clamp(value, min, max) — Constrain to range', boost: 14 },
  { label: 'map', kind: 'function', detail: 'map(val, inMin, inMax, outMin, outMax) — Map between ranges', boost: 12 },
  { label: 'floor', kind: 'function', detail: 'floor(x) — Round down', boost: 8 },
  { label: 'ceil', kind: 'function', detail: 'ceil(x) — Round up', boost: 8 },
  { label: 'round', kind: 'function', detail: 'round(x) — Round to nearest', boost: 8 },
  { label: 'trunc', kind: 'function', detail: 'trunc(x) — Truncate decimal', boost: 6 },
  { label: 'abs', kind: 'function', detail: 'abs(x) — Absolute value', boost: 10 },
  { label: 'sign', kind: 'function', detail: 'sign(x) — Sign (-1, 0, or 1)', boost: 6 },
  { label: 'min', kind: 'function', detail: 'min(a, b, ...) — Minimum', boost: 10 },
  { label: 'max', kind: 'function', detail: 'max(a, b, ...) — Maximum', boost: 10 },
  { label: 'polarX', kind: 'function', detail: 'polarX(cx, angle, radius) — X component of polar coordinate', boost: 8 },
  { label: 'polarY', kind: 'function', detail: 'polarY(cy, angle, radius) — Y component of polar coordinate', boost: 8 },
  { label: 'random', kind: 'function', detail: 'random() — Random 0-1', boost: 8 },
  { label: 'randomRange', kind: 'function', detail: 'randomRange(min, max) — Random in range', boost: 8 },
  { label: 'exp', kind: 'function', detail: 'exp(x) — e^x', boost: 6 },
  { label: 'log', kind: 'function', detail: 'log(...) — Natural log or debug log', boost: 8 },
  { label: 'log10', kind: 'function', detail: 'log10(x) — Base-10 log', boost: 6 },
  { label: 'log2', kind: 'function', detail: 'log2(x) — Base-2 log', boost: 6 },
  { label: 'pow', kind: 'function', detail: 'pow(x, y) — x^y', boost: 8 },
  { label: 'sqrt', kind: 'function', detail: 'sqrt(x) — Square root', boost: 10 },
  { label: 'cbrt', kind: 'function', detail: 'cbrt(x) — Cube root', boost: 6 },
  { label: 'ctx', kind: 'variable', detail: 'ctx — Path context (position, start, heading)', boost: 16 },
  { label: 'Object', kind: 'variable', detail: 'Object — Static methods (keys, values, entries)', boost: 6 },
  { label: 'Color', kind: 'variable', detail: 'Color — Color creation and manipulation', boost: 8 },
];

/** Type member completion sets keyed by Pathogen type name */
export const TYPE_MEMBERS: Record<string, MemberCompletionSet> = {
  'Point': {
    properties: [
      { label: 'x', kind: 'property', detail: 'X coordinate', boost: 8 },
      { label: 'y', kind: 'property', detail: 'Y coordinate', boost: 8 },
    ],
    methods: [
      { label: 'translate', kind: 'function', detail: 'translate(dx, dy) — Offset point', boost: 8 },
      { label: 'rotate', kind: 'function', detail: 'rotate(angle, origin?) — Rotate around point', boost: 8 },
      { label: 'distanceTo', kind: 'function', detail: 'distanceTo(other) — Euclidean distance', boost: 8 },
      { label: 'angleTo', kind: 'function', detail: 'angleTo(other) — Angle to other point', boost: 8 },
      { label: 'lerp', kind: 'function', detail: 'lerp(other, t) — Interpolate toward point', boost: 8 },
      { label: 'midpoint', kind: 'function', detail: 'midpoint(other) — Midpoint between two points', boost: 8 },
      { label: 'polarTranslate', kind: 'function', detail: 'polarTranslate(angle, distance) — Polar offset', boost: 8 },
      { label: 'offset', kind: 'function', detail: 'offset(other) — Get {dx, dy} delta', boost: 8 },
    ],
  },
  'array': {
    properties: [
      { label: 'length', kind: 'property', detail: 'Number of elements', boost: 8 },
    ],
    methods: [
      { label: 'push', kind: 'function', detail: 'push(item) — Add to end', boost: 8 },
      { label: 'pop', kind: 'function', detail: 'pop() — Remove and return last element', boost: 8 },
      { label: 'shift', kind: 'function', detail: 'shift() — Remove and return first element', boost: 8 },
      { label: 'unshift', kind: 'function', detail: 'unshift(item) — Add to beginning', boost: 8 },
      { label: 'empty', kind: 'function', detail: 'empty() — Check if array is empty', boost: 8 },
      { label: 'map', kind: 'function', detail: 'map {|item| ...} — Transform elements', boost: 8 },
      { label: 'reduce', kind: 'function', detail: 'reduce(init) {|acc, item| ...} — Reduce', boost: 8 },
      { label: 'mapSlice', kind: 'function', detail: 'mapSlice(length) — Sliding window slices', boost: 8 },
      { label: 'slice', kind: 'function', detail: 'slice(start, end?) — Get sub-array', boost: 8 },
    ],
  },
  'string': {
    properties: [
      { label: 'length', kind: 'property', detail: 'String length', boost: 8 },
    ],
    methods: [
      { label: 'split', kind: 'function', detail: 'split() — Split into character array', boost: 8 },
      { label: 'append', kind: 'function', detail: 'append(str) — Concatenate', boost: 8 },
      { label: 'prepend', kind: 'function', detail: 'prepend(str) — Prepend string', boost: 8 },
      { label: 'includes', kind: 'function', detail: 'includes(str) — Check if contains', boost: 8 },
      { label: 'slice', kind: 'function', detail: 'slice(start, end?) — Get substring', boost: 8 },
      { label: 'empty', kind: 'function', detail: 'empty() — Check if empty', boost: 8 },
    ],
  },
  'PathBlock': {
    properties: [
      { label: 'length', kind: 'property', detail: 'Path length', boost: 8 },
      { label: 'vertices', kind: 'property', detail: 'Vertex points', boost: 8 },
      { label: 'subPathCount', kind: 'property', detail: 'Number of subpaths', boost: 8 },
      { label: 'subPathCommands', kind: 'property', detail: 'Array of command objects', boost: 8 },
      { label: 'startPoint', kind: 'property', detail: 'First point', boost: 8 },
      { label: 'endPoint', kind: 'property', detail: 'Last point', boost: 8 },
      { label: 'advanceWidth', kind: 'property', detail: 'Glyph advance width', boost: 8 },
      { label: 'contours', kind: 'property', detail: 'Per-contour PathBlocks', boost: 8 },
    ],
    methods: [
      { label: 'draw', kind: 'function', detail: 'draw() — Emit path data', boost: 8 },
      { label: 'drawTo', kind: 'function', detail: 'drawTo(layerName) — Emit to layer', boost: 8 },
      { label: 'get', kind: 'function', detail: 'get(t) — Sample point at t', boost: 8 },
      { label: 'tangent', kind: 'function', detail: 'tangent(t) — Tangent angle at t', boost: 8 },
      { label: 'normal', kind: 'function', detail: 'normal(t) — Normal angle at t', boost: 8 },
      { label: 'partition', kind: 'function', detail: 'partition(n) — Split into segments', boost: 8 },
      { label: 'reverse', kind: 'function', detail: 'reverse() — Reverse direction', boost: 8 },
      { label: 'boundingBox', kind: 'function', detail: 'boundingBox() — Get bounding box', boost: 8 },
      { label: 'offset', kind: 'function', detail: 'offset(distance) — Offset path', boost: 8 },
      { label: 'mirror', kind: 'function', detail: 'mirror(angle) — Mirror path', boost: 8 },
      { label: 'scale', kind: 'function', detail: 'scale(sx, sy) — Scale path', boost: 8 },
      { label: 'rotateAtVertexIndex', kind: 'function', detail: 'rotateAtVertexIndex(index, angle) — Rotate at vertex', boost: 8 },
      { label: 'subPath', kind: 'function', detail: 'subPath(startT, endT) — Extract sub-path', boost: 8 },
      { label: 'project', kind: 'function', detail: 'project(x, y) — Project to position', boost: 8 },
      { label: 'chamfer', kind: 'function', detail: 'chamfer(distance) — Chamfer all corners', boost: 8 },
      { label: 'chamferAtVertex', kind: 'function', detail: 'chamferAtVertex(index, distance) — Chamfer at vertex', boost: 8 },
      { label: 'fillet', kind: 'function', detail: 'fillet(radius) — Round all corners', boost: 8 },
      { label: 'filletAtVertex', kind: 'function', detail: 'filletAtVertex(index, radius) — Round at vertex', boost: 8 },
      { label: 'ellipticalFillet', kind: 'function', detail: 'ellipticalFillet(rx, ry) — Elliptical fillet', boost: 8 },
      { label: 'ellipticalFilletAtVertex', kind: 'function', detail: 'ellipticalFilletAtVertex(index, rx, ry) — Elliptical fillet at vertex', boost: 8 },
      { label: 'union', kind: 'function', detail: 'union(other) — Boolean union', boost: 8 },
      { label: 'difference', kind: 'function', detail: 'difference(other) — Boolean difference', boost: 8 },
      { label: 'intersection', kind: 'function', detail: 'intersection(other) — Boolean intersection', boost: 8 },
      { label: 'xor', kind: 'function', detail: 'xor(other) — Boolean XOR', boost: 8 },
      { label: 'intersects', kind: 'function', detail: 'intersects(other) — Check for intersections', boost: 8 },
      { label: 'intersectionPoints', kind: 'function', detail: 'intersectionPoints(other) — Get intersection points', boost: 8 },
    ],
  },
  'PolarVector': {
    properties: [
      { label: 'angle', kind: 'property', detail: 'Angle in radians', boost: 8 },
      { label: 'distance', kind: 'property', detail: 'Distance magnitude', boost: 8 },
    ],
    methods: [
      { label: 'turn', kind: 'function', detail: 'turn(delta) — Turn by angle delta', boost: 8 },
      { label: 'scale', kind: 'function', detail: 'scale(factor) — Scale distance', boost: 8 },
      { label: 'mirror', kind: 'function', detail: 'mirror() — Flip direction', boost: 8 },
    ],
  },
  'Cycler': {
    properties: [
      { label: 'length', kind: 'property', detail: 'Number of elements', boost: 8 },
    ],
    methods: [
      { label: 'pick', kind: 'function', detail: 'pick() — Get next element', boost: 8 },
    ],
  },
  'SVGFragment': {
    properties: [

    ],
    methods: [
      { label: 'insert', kind: 'function', detail: 'insert() — Insert fragment into layer', boost: 8 },
    ],
  },
  'TextLayer': {
    properties: [
      { label: 'name', kind: 'property', detail: 'Layer name', boost: 8 },
      { label: 'styles', kind: 'property', detail: 'Style block', boost: 8 },
    ],
    methods: [

    ],
  },
  'PathLayer': {
    properties: [
      { label: 'name', kind: 'property', detail: 'Layer name', boost: 8 },
      { label: 'styles', kind: 'property', detail: 'Style block', boost: 8 },
      { label: 'ctx', kind: 'property', detail: 'Path context (position, heading, transform)', boost: 8 },
    ],
    methods: [

    ],
  },
  'GroupLayer': {
    properties: [
      { label: 'name', kind: 'property', detail: 'Layer name', boost: 8 },
      { label: 'styles', kind: 'property', detail: 'Style block', boost: 8 },
      { label: 'ctx', kind: 'property', detail: 'Path context (position, heading, transform)', boost: 8 },
    ],
    methods: [
      { label: 'append', kind: 'function', detail: 'append(layer) — Add child layer', boost: 8 },
    ],
  },
  'PathContext': {
    properties: [
      { label: 'position', kind: 'property', detail: 'Current pen position {x, y}', boost: 8 },
      { label: 'start', kind: 'property', detail: 'Subpath start position {x, y}', boost: 8 },
      { label: 'heading', kind: 'property', detail: 'Current heading angle', boost: 10 },
      { label: 'tangentAngle', kind: 'property', detail: 'Tangent angle at current position', boost: 8 },
      { label: 'transform', kind: 'property', detail: 'Layer transform state', boost: 8 },
      { label: 'commands', kind: 'property', detail: 'Array of executed commands', boost: 8 },
    ],
    methods: [

    ],
  },
  'ObjectValue': {
    properties: [
      { label: 'length', kind: 'property', detail: 'Number of properties', boost: 8 },
    ],
    methods: [
      { label: 'has', kind: 'function', detail: 'has(key) — Check if key exists', boost: 8 },
    ],
  },
  'ProjectedText': {
    properties: [
      { label: 'elementCount', kind: 'property', detail: 'Number of text elements', boost: 8 },
      { label: 'styles', kind: 'property', detail: 'Style block', boost: 8 },
      { label: 'origin', kind: 'property', detail: 'Origin point', boost: 8 },
    ],
    methods: [
      { label: 'translate', kind: 'function', detail: 'translate(dx, dy) — Offset projected text', boost: 8 },
    ],
  },
  'CSSVar': {
    properties: [

    ],
    methods: [

    ],
  },
};

/** Namespace member completion sets keyed by namespace name */
export const NAMESPACE_MEMBERS: Record<string, MemberCompletionSet> = {
  'Object': {
    properties: [

    ],
    methods: [
      { label: 'keys', kind: 'function', detail: 'Object.keys(obj) — Get keys', boost: 8 },
      { label: 'values', kind: 'function', detail: 'Object.values(obj) — Get values', boost: 8 },
      { label: 'entries', kind: 'function', detail: 'Object.entries(obj) — Key-value pairs', boost: 8 },
      { label: 'delete', kind: 'function', detail: 'Object.delete(obj, key) — Remove key', boost: 8 },
      { label: 'has', kind: 'function', detail: 'Object.has(obj, key) — Check if key exists', boost: 8 },
    ],
  },
  'Color': {
    properties: [

    ],
    methods: [
      { label: 'mix', kind: 'function', detail: 'Color.mix(c1, c2, t) — Interpolate colors', boost: 8 },
      { label: 'palette', kind: 'function', detail: 'Color.palette(color, n) — Generate palette', boost: 8 },
      { label: 'lightDark', kind: 'function', detail: 'Color.lightDark(light, dark) — Theme-aware color', boost: 8 },
    ],
  },
};
