// AUTO-GENERATED by scripts/generate-completions.ts — DO NOT EDIT
// Source: src/api-surface.ts + src/evaluator/index.ts (BUILTIN_ENUMS)
// Regenerate: npm run generate:completions

import type { CompletionEntry } from './completion-data';

/** Top-level enum name completions (GridPatternType, Easing, etc.) */
export const ENUM_COMPLETIONS: CompletionEntry[] = [
  { label: 'BBoxAnchor', kind: 'variable', detail: 'Bounding box anchor position', boost: 8 },
  { label: 'ConicSpread', kind: 'variable', detail: 'Conic gradient edge behavior', boost: 6 },
  { label: 'Direction', kind: 'variable', detail: 'Rotation direction (CW/CCW)', boost: 8 },
  { label: 'Easing', kind: 'variable', detail: 'Easing function for interpolation', boost: 10 },
  { label: 'GradientUnits', kind: 'variable', detail: 'Gradient coordinate system', boost: 6 },
  { label: 'GridPatternType', kind: 'variable', detail: 'Grid cell rendering mode', boost: 10 },
  { label: 'HexagonOrientation', kind: 'variable', detail: 'Hexagon grid orientation', boost: 8 },
  { label: 'InnerFill', kind: 'variable', detail: 'Conic gradient inner fill mode', boost: 6 },
  { label: 'Interpolation', kind: 'variable', detail: 'Color interpolation space', boost: 8 },
  { label: 'SpreadMethod', kind: 'variable', detail: 'Gradient spread method', boost: 8 },
  { label: 'TopoMethod', kind: 'variable', detail: 'Topological gradient method', boost: 6 },
  { label: 'VerticalAnchor', kind: 'variable', detail: 'Text vertical alignment anchor', boost: 8 },
];

/** Enum member completions keyed by enum name */
export const ENUM_MEMBER_MAP: Record<string, CompletionEntry[]> = {
  BBoxAnchor: [
    { label: 'TopLeft', kind: 'constant', detail: 'BBoxAnchor.TopLeft → "top-left"', boost: 8 },
    { label: 'Top', kind: 'constant', detail: 'BBoxAnchor.Top → "top"', boost: 8 },
    { label: 'TopRight', kind: 'constant', detail: 'BBoxAnchor.TopRight → "top-right"', boost: 8 },
    { label: 'Right', kind: 'constant', detail: 'BBoxAnchor.Right → "right"', boost: 8 },
    { label: 'BottomRight', kind: 'constant', detail: 'BBoxAnchor.BottomRight → "bottom-right"', boost: 8 },
    { label: 'Bottom', kind: 'constant', detail: 'BBoxAnchor.Bottom → "bottom"', boost: 8 },
    { label: 'BottomLeft', kind: 'constant', detail: 'BBoxAnchor.BottomLeft → "bottom-left"', boost: 8 },
    { label: 'Left', kind: 'constant', detail: 'BBoxAnchor.Left → "left"', boost: 8 },
    { label: 'Center', kind: 'constant', detail: 'BBoxAnchor.Center → "center"', boost: 8 },
  ],
  ConicSpread: [
    { label: 'Clamp', kind: 'constant', detail: 'ConicSpread.Clamp → "clamp"', boost: 8 },
    { label: 'Repeat', kind: 'constant', detail: 'ConicSpread.Repeat → "repeat"', boost: 8 },
    { label: 'Transparent', kind: 'constant', detail: 'ConicSpread.Transparent → "transparent"', boost: 8 },
  ],
  Direction: [
    { label: 'CW', kind: 'constant', detail: 'Direction.CW → "cw"', boost: 8 },
    { label: 'CCW', kind: 'constant', detail: 'Direction.CCW → "ccw"', boost: 8 },
  ],
  Easing: [
    { label: 'Linear', kind: 'constant', detail: 'Easing.Linear → "linear"', boost: 8 },
    { label: 'Smoothstep', kind: 'constant', detail: 'Easing.Smoothstep → "smoothstep"', boost: 8 },
    { label: 'EaseIn', kind: 'constant', detail: 'Easing.EaseIn → "ease-in"', boost: 8 },
    { label: 'EaseOut', kind: 'constant', detail: 'Easing.EaseOut → "ease-out"', boost: 8 },
    { label: 'EaseInOut', kind: 'constant', detail: 'Easing.EaseInOut → "ease-in-out"', boost: 8 },
  ],
  GradientUnits: [
    { label: 'ObjectBoundingBox', kind: 'constant', detail: 'GradientUnits.ObjectBoundingBox → "objectBoundingBox"', boost: 8 },
    { label: 'UserSpaceOnUse', kind: 'constant', detail: 'GradientUnits.UserSpaceOnUse → "userSpaceOnUse"', boost: 8 },
  ],
  GridPatternType: [
    { label: 'Shape', kind: 'constant', detail: 'GridPatternType.Shape → "shape"', boost: 8 },
    { label: 'Dot', kind: 'constant', detail: 'GridPatternType.Dot → "dot"', boost: 8 },
    { label: 'Intersection', kind: 'constant', detail: 'GridPatternType.Intersection → "intersection"', boost: 8 },
    { label: 'Partial', kind: 'constant', detail: 'GridPatternType.Partial → "partial"', boost: 8 },
  ],
  HexagonOrientation: [
    { label: 'Edge', kind: 'constant', detail: 'HexagonOrientation.Edge → "edge"', boost: 8 },
    { label: 'Vertex', kind: 'constant', detail: 'HexagonOrientation.Vertex → "vertex"', boost: 8 },
  ],
  InnerFill: [
    { label: 'Transparent', kind: 'constant', detail: 'InnerFill.Transparent → "transparent"', boost: 8 },
    { label: 'TransparentBlend', kind: 'constant', detail: 'InnerFill.TransparentBlend → "transparent-blend"', boost: 8 },
    { label: 'Center', kind: 'constant', detail: 'InnerFill.Center → "center"', boost: 8 },
  ],
  Interpolation: [
    { label: 'SRGB', kind: 'constant', detail: 'Interpolation.SRGB → "srgb"', boost: 8 },
    { label: 'OKLCH', kind: 'constant', detail: 'Interpolation.OKLCH → "oklch"', boost: 8 },
    { label: 'LinearRGB', kind: 'constant', detail: 'Interpolation.LinearRGB → "linearRGB"', boost: 8 },
  ],
  SpreadMethod: [
    { label: 'Pad', kind: 'constant', detail: 'SpreadMethod.Pad → "pad"', boost: 8 },
    { label: 'Reflect', kind: 'constant', detail: 'SpreadMethod.Reflect → "reflect"', boost: 8 },
    { label: 'Repeat', kind: 'constant', detail: 'SpreadMethod.Repeat → "repeat"', boost: 8 },
  ],
  TopoMethod: [
    { label: 'Distance', kind: 'constant', detail: 'TopoMethod.Distance → "distance"', boost: 8 },
    { label: 'Laplace', kind: 'constant', detail: 'TopoMethod.Laplace → "laplace"', boost: 8 },
  ],
  VerticalAnchor: [
    { label: 'Descender', kind: 'constant', detail: 'VerticalAnchor.Descender → "descender"', boost: 8 },
    { label: 'Baseline', kind: 'constant', detail: 'VerticalAnchor.Baseline → "baseline"', boost: 8 },
    { label: 'Midline', kind: 'constant', detail: 'VerticalAnchor.Midline → "midline"', boost: 8 },
    { label: 'CapHeight', kind: 'constant', detail: 'VerticalAnchor.CapHeight → "cap-height"', boost: 8 },
  ],
};
