import * as esbuild from 'esbuild';
import { promises as fs } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Command } from 'commander';

import { buildPlayground } from './build-playground.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
// Output to 'public' - standard CloudFlare Pages output directory
const DIST = join(ROOT, 'public');

async function copyDir(src: string, dest: string): Promise<void> {
  await fs.mkdir(dest, { recursive: true });
  const entries = await fs.readdir(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = join(src, entry.name);
    const destPath = join(dest, entry.name);

    if (entry.isDirectory()) {
      await copyDir(srcPath, destPath);
    } else {
      await fs.copyFile(srcPath, destPath);
    }
  }
}

async function copyFile(src: string, dest: string): Promise<void> {
  await fs.mkdir(dirname(dest), { recursive: true });
  await fs.copyFile(src, dest);
}

async function build(): Promise<void> {
  console.log('Building website to public/...\n');

  // Clean dist/website
  try {
    await fs.rm(DIST, { recursive: true });
  } catch {
    // Directory doesn't exist, that's fine
  }
  await fs.mkdir(DIST, { recursive: true });

  // Copy website root files
  console.log('Copying website root...');
  await copyFile(join(ROOT, 'website', 'index.html'), join(DIST, 'index.html'));

  // Copy website assets (landing background SVG, etc.)
  const websiteAssetsDir = join(ROOT, 'website', 'assets');
  try {
    await fs.stat(websiteAssetsDir);
    await copyDir(websiteAssetsDir, join(DIST, 'assets'));
    console.log('Copied website assets.');
  } catch {
    // assets/ directory doesn't exist yet — skip
  }
  await esbuild.build({
    entryPoints: [join(ROOT, 'website', '_worker.ts')],
    outfile: join(DIST, '_worker.js'),
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    bundle: false,
  });

  // Build playground (esbuild transpile + asset copy) → public/pathogen/
  console.log('Building playground...');
  await buildPlayground();

  const pathogenDest = join(DIST, 'pathogen');

  // Copy library dist (for global script tag)
  console.log('Copying library dist...');
  await fs.mkdir(join(pathogenDest, 'dist'), { recursive: true });
  await copyFile(join(ROOT, 'dist', 'index.global.js'), join(pathogenDest, 'dist', 'index.global.js'));
  // Also copy source map if it exists
  try {
    await copyFile(join(ROOT, 'dist', 'index.global.js.map'), join(pathogenDest, 'dist', 'index.global.js.map'));
  } catch {
    // Map file doesn't exist, that's fine
  }

  // Copy worker file for async compilation
  console.log('Copying worker...');
  try {
    await copyFile(join(ROOT, 'dist', 'worker.worker.js'), join(pathogenDest, 'dist', 'worker.worker.js'));
    // Also copy worker source map if it exists
    try {
      await copyFile(join(ROOT, 'dist', 'worker.worker.js.map'), join(pathogenDest, 'dist', 'worker.worker.js.map'));
    } catch {
      // Map file doesn't exist, that's fine
    }
  } catch {
    console.warn('  Worker file not found, skipping...');
  }

  // Copy static docs page if it exists
  try {
    const docsStaticSrc = join(ROOT, 'website', 'docs-static');
    const docsStaticDest = join(pathogenDest, 'docs');
    await fs.access(docsStaticSrc);
    console.log('Copying static docs page...');
    await copyDir(docsStaticSrc, docsStaticDest);
  } catch {
    console.warn('  Static docs page not found (run build:docs first)');
  }

  // Copy static blog pages (generated by build-blog.ts)
  try {
    const blogStaticSrc = join(ROOT, 'website', 'blog-static');
    const blogStaticDest = join(pathogenDest, 'blog');
    await fs.access(blogStaticSrc);
    console.log('Copying static blog pages...');
    await copyDir(blogStaticSrc, blogStaticDest);
  } catch {
    console.warn('  Static blog pages not found (run build:blog first)');
  }

  // Copy blog sample SVGs (referenced by mini-workspace components)
  try {
    const blogSamplesDir = join(ROOT, 'website', 'blog', 'samples');
    await fs.access(blogSamplesDir);
    console.log('Copying blog samples...');
    await copyDir(blogSamplesDir, join(pathogenDest, 'blog', 'samples'));
  } catch {
    // No samples directory, that's fine
  }

  // Generate robots.txt
  console.log('Generating robots.txt...');
  const robotsTxt = `User-agent: *
Allow: /pathogen/docs
Allow: /pathogen/docs/docs.md
Allow: /pathogen/explore
Allow: /pathogen/featured
Allow: /pathogen/blog
Disallow: /pathogen/api/
Disallow: /pathogen/workspace/
Disallow: /pathogen/preferences
Disallow: /pathogen/admin/
Disallow: /pathogen/storybook
Sitemap: https://pedestal.design/sitemap.xml
Content-Signal: search=yes, ai-input=yes, ai-train=no
`;
  await fs.writeFile(join(DIST, 'robots.txt'), robotsTxt);

  // Generate sitemap.xml
  console.log('Generating sitemap.xml...');
  const today = new Date().toISOString().split('T')[0];

  // Discover blog post slugs from markdown files
  let blogSlugs: string[] = [];
  try {
    const blogDir = join(ROOT, 'website', 'blog');
    const blogFiles = await fs.readdir(blogDir);
    blogSlugs = blogFiles.filter((f) => f.endsWith('.md')).map((f) => f.replace('.md', ''));
  } catch {
    /* no blog dir */
  }

  const blogUrls = [
    `  <url>
    <loc>https://pedestal.design/pathogen/blog</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.6</priority>
  </url>`,
    ...blogSlugs.map(
      (slug) =>
        `  <url>
    <loc>https://pedestal.design/pathogen/blog/${slug}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>`,
    ),
  ];

  const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://pedestal.design/pathogen/docs</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://pedestal.design/pathogen/docs/docs.md</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://pedestal.design/pathogen/explore</loc>
    <lastmod>${today}</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://pedestal.design/pathogen/featured</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
${blogUrls.join('\n')}
</urlset>
`;
  await fs.writeFile(join(DIST, 'sitemap.xml'), sitemapXml);

  console.log('\nBuild complete!');
  console.log(`Output: ${DIST}`);
}

const program = new Command();
program
  .name('build-website')
  .description('Build website for CloudFlare Pages deployment')
  .action(async () => {
    try {
      await build();
    } catch (err) {
      console.error('Build failed:', err);
      process.exit(1);
    }
  });
program.parse();
