import * as esbuild from 'esbuild';
import { promises as fs } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Command } from 'commander';

import { buildPlayground } from './build-playground.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
// Output to 'public' - standard CloudFlare Pages output directory
const DIST = join(ROOT, 'public');

async function copyDir(src: string, dest: string): Promise<void> {
  await fs.mkdir(dest, { recursive: true });
  const entries = await fs.readdir(src, { withFileTypes: true });

  for (const entry of entries) {
    const srcPath = join(src, entry.name);
    const destPath = join(dest, entry.name);

    if (entry.isDirectory()) {
      await copyDir(srcPath, destPath);
    } else {
      await fs.copyFile(srcPath, destPath);
    }
  }
}

async function copyFile(src: string, dest: string): Promise<void> {
  await fs.mkdir(dirname(dest), { recursive: true });
  await fs.copyFile(src, dest);
}

async function codegenVersion(): Promise<void> {
  // Read package.json's `version` and emit a tiny TS module that both the
  // SPA (via site-header-template.ts) and the Pages worker (via the
  // homepage footer in _worker.ts) import. Single source of truth lives
  // in package.json so a release bump there flows automatically through
  // the website's visible version subtitles.
  const pkgRaw = await fs.readFile(join(ROOT, 'package.json'), 'utf-8');
  const pkg = JSON.parse(pkgRaw) as { version: string };
  const out = `// Auto-generated from package.json by scripts/build-website.ts.
// Do not edit by hand — your change will be clobbered on the next build.

export const PATHOGEN_VERSION = ${JSON.stringify(pkg.version)};
`;
  await fs.writeFile(join(ROOT, 'playground', 'utils', 'version.ts'), out);
  console.log(`Generated playground/utils/version.ts (PATHOGEN_VERSION = ${pkg.version}).`);
}

async function build(): Promise<void> {
  console.log('Building website to public/...\n');

  // Clean dist/website
  try {
    await fs.rm(DIST, { recursive: true });
  } catch {
    // Directory doesn't exist, that's fine
  }
  await fs.mkdir(DIST, { recursive: true });

  // Codegen version before any bundler reads source files.
  await codegenVersion();

  // The Pages worker's renderHomepage() now claims `/`, so we no longer
  // copy a static apex landing page (the old Pedestal-Design redirect at
  // public/index.html). The SPA shell lives at /spa.html (written by
  // buildPlayground) — kept distinct from / so it doesn't collide with
  // the SSR'd homepage.

  // Copy website assets (landing background SVG, email wordmark, etc.)
  const websiteAssetsDir = join(ROOT, 'website', 'assets');
  try {
    await fs.stat(websiteAssetsDir);
    await copyDir(websiteAssetsDir, join(DIST, 'assets'));
    console.log('Copied website assets.');
  } catch {
    // assets/ directory doesn't exist yet — skip
  }
  await esbuild.build({
    entryPoints: [join(ROOT, 'website', '_worker.ts')],
    outfile: join(DIST, '_worker.js'),
    format: 'esm',
    platform: 'neutral',
    target: 'es2022',
    bundle: true,
  });

  // Build playground (esbuild transpile + asset copy + dist artifacts) →
  // public/. buildPlayground() now stages dist/index.global.js and
  // dist/worker.worker.js as part of its own output, so we don't duplicate
  // that copy here. Anyone running `npm run build:playground` standalone
  // gets a fully-functional playground without needing build:website.
  console.log('Building playground...');
  await buildPlayground();

  // Copy static docs page if it exists
  try {
    const docsStaticSrc = join(ROOT, 'website', 'docs-static');
    const docsStaticDest = join(DIST, 'docs');
    await fs.access(docsStaticSrc);
    console.log('Copying static docs page...');
    await copyDir(docsStaticSrc, docsStaticDest);
  } catch {
    console.warn('  Static docs page not found (run build:docs first)');
  }

  // Copy static blog pages (generated by build-blog.ts)
  try {
    const blogStaticSrc = join(ROOT, 'website', 'blog-static');
    const blogStaticDest = join(DIST, 'blog');
    await fs.access(blogStaticSrc);
    console.log('Copying static blog pages...');
    await copyDir(blogStaticSrc, blogStaticDest);
  } catch {
    console.warn('  Static blog pages not found (run build:blog first)');
  }

  // Copy blog sample SVGs (referenced by mini-workspace components)
  try {
    const blogSamplesDir = join(ROOT, 'website', 'blog', 'samples');
    await fs.access(blogSamplesDir);
    console.log('Copying blog samples...');
    await copyDir(blogSamplesDir, join(DIST, 'blog', 'samples'));
  } catch {
    // No samples directory, that's fine
  }

  // Generate robots.txt
  console.log('Generating robots.txt...');
  const robotsTxt = `User-agent: *
Allow: /docs
Allow: /docs/docs.md
Allow: /explore
Allow: /featured
Allow: /blog
Disallow: /api/
Disallow: /workspace/
Disallow: /preferences
Disallow: /admin/
Disallow: /storybook
Sitemap: https://pathogen.studio/sitemap.xml
Content-Signal: search=yes, ai-input=yes, ai-train=no
`;
  await fs.writeFile(join(DIST, 'robots.txt'), robotsTxt);

  // Generate sitemap.xml
  console.log('Generating sitemap.xml...');
  const today = new Date().toISOString().split('T')[0];

  // Discover blog post slugs from markdown files
  let blogSlugs: string[] = [];
  try {
    const blogDir = join(ROOT, 'website', 'blog');
    const blogFiles = await fs.readdir(blogDir);
    blogSlugs = blogFiles.filter((f) => f.endsWith('.md')).map((f) => f.replace('.md', ''));
  } catch {
    /* no blog dir */
  }

  const blogUrls = [
    `  <url>
    <loc>https://pathogen.studio/blog</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.6</priority>
  </url>`,
    ...blogSlugs.map(
      (slug) =>
        `  <url>
    <loc>https://pathogen.studio/blog/${slug}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.5</priority>
  </url>`,
    ),
  ];

  const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://pathogen.studio/docs</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://pathogen.studio/docs/docs.md</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://pathogen.studio/explore</loc>
    <lastmod>${today}</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://pathogen.studio/featured</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.7</priority>
  </url>
${blogUrls.join('\n')}
</urlset>
`;
  await fs.writeFile(join(DIST, 'sitemap.xml'), sitemapXml);

  console.log('\nBuild complete!');
  console.log(`Output: ${DIST}`);
}

const program = new Command();
program
  .name('build-website')
  .description('Build website for CloudFlare Pages deployment')
  .action(async () => {
    try {
      await build();
    } catch (err) {
      console.error('Build failed:', err);
      process.exit(1);
    }
  });
program.parse();
