// Generate the "Pathogen Studio" wordmark PNG used in the email footer.
//
// Run once per brand-name change:
//   npx tsx scripts/generate-email-wordmark.ts
//
// Outputs:
//   website/assets/email-wordmark.png  — preview / archived asset
//   website/auth/email-wordmark.ts     — base64 data URL constant for the worker
//
// We bake the data URL into the worker bundle (rather than fetching at runtime
// or referencing a public URL) so the email is self-contained and works even
// before the next site deploy. ~5-10 KB at this size; the wordmark is the
// only image in the email.

import { promises as fs } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import puppeteer from 'puppeteer';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const TEXT = 'Pathogen Studio';
const COLOR = '#1a1a2e';     // matches email H1 color
// Render at 2x for retina; CSS-display ~140 × 28 in email.
const FONT_SIZE_PX = 56;
const PADDING_X = 4;
const PADDING_Y = 4;

async function main(): Promise<void> {
  console.log(`Generating wordmark "${TEXT}" in Baumans @ ${FONT_SIZE_PX}px...`);

  const browser = await puppeteer.launch({ headless: true });
  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 800, height: 200, deviceScaleFactor: 1 });

    const html = `<!DOCTYPE html>
<html><head>
<meta charset="utf-8">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Baumans&display=swap" rel="stylesheet">
<style>
  html, body { margin: 0; padding: 0; background: transparent; }
  #wordmark {
    display: inline-block;
    font-family: 'Baumans', cursive;
    font-size: ${FONT_SIZE_PX}px;
    line-height: 1;
    color: ${COLOR};
    padding: ${PADDING_Y}px ${PADDING_X}px;
    white-space: nowrap;
  }
</style>
</head>
<body><div id="wordmark">${TEXT}</div></body></html>`;

    await page.setContent(html, { waitUntil: 'networkidle0' });
    await page.evaluate(() => (document as Document & { fonts: { ready: Promise<void> } }).fonts.ready);

    const handle = await page.$('#wordmark');
    if (!handle) throw new Error('wordmark element not found');

    const png = (await handle.screenshot({ type: 'png', omitBackground: true })) as Buffer;

    const outPng = join(ROOT, 'website', 'assets', 'email-wordmark.png');
    await fs.mkdir(dirname(outPng), { recursive: true });
    await fs.writeFile(outPng, png);
    console.log(`  wrote ${outPng} (${png.length} bytes)`);

    const dataUrl = `data:image/png;base64,${png.toString('base64')}`;
    const tsModule = `// Auto-generated by scripts/generate-email-wordmark.ts. Do not edit by hand.
// Regenerate after any change to the email brand name (env.AUTH_PRODUCT_NAME).
//
// Source: "${TEXT}" rendered in Baumans @ ${FONT_SIZE_PX}px, ${COLOR} on transparent.

export const EMAIL_WORDMARK_TEXT = ${JSON.stringify(TEXT)};
export const EMAIL_WORDMARK_DATA_URL = ${JSON.stringify(dataUrl)};
`;
    const outTs = join(ROOT, 'website', 'auth', 'email-wordmark.ts');
    await fs.writeFile(outTs, tsModule);
    console.log(`  wrote ${outTs} (${tsModule.length} bytes; data URL ~${Math.ceil(dataUrl.length / 1024)} KB)`);
  } finally {
    await browser.close();
  }

  console.log('Done.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
