import { Command } from 'commander';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { BUILTIN_ENUMS, ENUM_METADATA } from '../src/api-surface';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const program = new Command();
program
  .name('generate-completions')
  .description('Generate completion data from API surface registry')
  .action(() => {
    const outputPath = path.resolve(__dirname, '../src/language-services/completion-data.generated.ts');

    // Cross-check: warn about missing metadata
    const missingMetadata = Object.keys(BUILTIN_ENUMS).filter((k) => !(k in ENUM_METADATA));
    if (missingMetadata.length > 0) {
      console.warn(`⚠ Missing ENUM_METADATA for: ${missingMetadata.join(', ')}`);
      console.warn('  Add entries in src/api-surface.ts');
    }

    // Generate enum top-level completions
    const enumNames = Object.keys(BUILTIN_ENUMS).sort();
    const enumCompletionEntries = enumNames.map((name) => {
      const meta = ENUM_METADATA[name] ?? { detail: `${name} enum`, boost: 6 };
      return `  { label: '${name}', kind: 'variable', detail: '${meta.detail}', boost: ${meta.boost} }`;
    });

    // Generate enum member maps
    const enumMemberEntries = enumNames.map((enumName) => {
      const members = BUILTIN_ENUMS[enumName];
      const memberEntries = Object.entries(members).map(([memberName, value]) => {
        return `    { label: '${memberName}', kind: 'constant', detail: '${enumName}.${memberName} → "${value}"', boost: 8 }`;
      });
      return `  ${enumName}: [\n${memberEntries.join(',\n')},\n  ]`;
    });

    // Build output
    const output = `// AUTO-GENERATED by scripts/generate-completions.ts — DO NOT EDIT
// Source: src/api-surface.ts + src/evaluator/index.ts (BUILTIN_ENUMS)
// Regenerate: npm run generate:completions

import type { CompletionEntry } from './completion-data';

/** Top-level enum name completions (GridPatternType, Easing, etc.) */
export const ENUM_COMPLETIONS: CompletionEntry[] = [
${enumCompletionEntries.join(',\n')},
];

/** Enum member completions keyed by enum name */
export const ENUM_MEMBER_MAP: Record<string, CompletionEntry[]> = {
${enumMemberEntries.join(',\n')},
};
`;

    fs.writeFileSync(outputPath, output, 'utf-8');
    console.log(`✓ Generated ${outputPath}`);
    console.log(`  ${enumNames.length} enums, ${Object.values(BUILTIN_ENUMS).reduce((n, m) => n + Object.keys(m).length, 0)} total members`);
  });

program.parse();
